blueprint:
  name: Bedside light on at time
  description: >
    Turn on a bedside light at a specified time if the person is home
    and the light is off.
  domain: automation
  input:
    person_entity:
      name: Person
      description: Person entity to check presence for.
      selector:
        entity:
          domain: person
    light_entity:
      name: Light
      selector:
        entity:
          domain: light
    time:
      name: Time
      description: Time at which to turn on the light.
      selector:
        time: {}

mode: single

trigger:
  - platform: time
    at: !input time

condition:
  - condition: state
    entity_id: !input person_entity
    state: home
  - condition: state
    entity_id: !input light_entity
    state: "off"

action:
  - service: light.turn_on
    data:
      transition: 5
    target:
      entity_id: !input light_entity
