blueprint:
  name: Hue Tap Dial for Zigbee2MQTT
  description: >
    Simple implementation for Hue Tap Dial for Zigbee2MQTT.
  domain: automation

  input:
    controller:
      name: (Zigbee2MQTT) Controller Name
      description: The name of the device in Zigbee2MQTT
      default: ""
    base_topic:
      name: Root/Base mqtt topic from Zigbee2MQTT
      description: The Root/base topic as configured in Zigbee2MQTT
      default: zigbee2mqtt

    button_1_press:
      name: Button 1 press
      description: Action for button 1 press
      default: []
      selector:
        action: {}

mode: restart

trigger_variables:
  base_topic: !input base_topic
  controller: !input controller

trigger:
  - platform: mqtt
    topic: "{{ base_topic ~ '/' ~ controller }}"

condition:
  - condition: template
    value_template: "{{ 'action' in trigger.payload_json and trigger.payload_json.action != '' }}"

action:
  - variables:
      controller: !input controller
      command: "{{ trigger.payload_json.action }}"
  - choose:
      - conditions: '{{ command == "button_1_press" }}'
        sequence: !input button_1_press
