blueprint:
  name: Light Disco
  description: >
    TODO

  domain: automation

  input:
    light_group_color:
      name: Single Zigbee group that contains all the color lights.
      description: >
        These are the lights used for the disco.
      selector:
        entity:
          domain: light
          multiple: false

    input_boolean_disco:
      name: Input boolean for disco.
      description: >
        Input boolean for disco toggle.
      selector:
        entity:
          domain: input_boolean
          multiple: false

mode: restart

trigger:
  - platform: state
    entity_id: !input input_boolean_disco
    to: "on"

action:
  - variables:
      input_boolean_entity: !input input_boolean_disco
  - repeat:
      while:
        # Need template rather than state condition such that it gets re-evaluated each loop:
        - condition: template
          value_template: "{{ states(input_boolean_entity) == 'on' }}"
      sequence:
        - service: light.turn_on
          data:
            transition: "{{ range(50, 150) | random / 100 }}"
            rgb_color:
              - "{{ range(0, 255) | random }}"
              - "{{ range(0, 255) | random  }}"
              - "{{ range(0, 255) | random  }}"
          target:
            entity_id: !input light_group_color
        - delay: "00:00:0{{ range(2, 5) | random }}"
