repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: home-assistant/config/blueprints/automation/custom/.+\.yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
