- binary_sensor:
    - name: "Dark Outside"
      icon: mdi:moon-waning-crescent
      state: >
        {{ state_attr('sun.sun', 'elevation') < 5 }}

    - name: "Low Illuminance Outside"
      icon: mdi:moon-waning-crescent
      state: >
        {{ states('sensor.illuminance') | int(0) < 10000 }}
