- binary_sensor:
    - unique_id: workstation_in_use
      device_class: occupancy
      name: "Workstation in use"
      state: >
        {{ states("sensor.plug_workstation_power") | float(0) > 60 }}
      delay_on:
        minutes: 1
      delay_off:
        minutes: 1

    - unique_id: entertainment_in_use
      device_class: occupancy
      name: "Entertainment in use"
      state: >
        {{ states("sensor.plug_entertainment_power") | float(0) > 50 }}
      delay_on:
        minutes: 1
      delay_off:
        minutes: 1
