homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1884
availability:
  enabled: true
serial:
  adapter: zstack
  port: tcp://192.168.1.131:6638
  baudrate: 115200
frontend:
  enabled: true
  port: 8080
advanced:
  transmit_power: 20
  channel: 25
  pan_id: 35539
  network_key: '!secret.yaml network_key'
  log_level: warning
  last_seen: ISO_8601
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
version: 4
devices:
  '0x0000000001732f4d':
    friendly_name: Switch Hall 0
    availability: false
  '0x001788010d12f602':
    friendly_name: Switch Tap Dial Living
  '0x0017880104f4f2b7':
    friendly_name: Switch Dimmer Living
  '0x001788010eee44ec':
    friendly_name: Light Hall 0 1
  '0x001788010ee66c15':
    friendly_name: Light Hall 0 2
  '0x001788010eee5b84':
    friendly_name: Light Hall 0 3
  '0x001788010ee656be':
    friendly_name: Light Hall 0 4
  '0x001788010eee1582':
    friendly_name: Light Living Entrance
  '0x84fd27fffe3b11f1':
    friendly_name: Light Living White Cabinet
  '0x001788010ee66d40':
    friendly_name: Light Bedroom JC Bed C
  '0x001788010ee652c5':
    friendly_name: Light Kitchen Middle 1
  '0x001788010ee652ae':
    friendly_name: Light Bedroom JC Bed J
  '0x001788010ee64599':
    friendly_name: Light Living Garden L1
  '0x001788010ee66ab7':
    friendly_name: Light Living Garden L2
  '0x001788010ee621ee':
    friendly_name: Light Living Garden R1
  '0x001788010ee621f5':
    friendly_name: Light Living Garden R2
  '0x001788010eee58e0':
    friendly_name: Light Living Wall Right 1
  '0x001788010eee39bb':
    friendly_name: Light Living Wall Right 2
  '0x001788010eee567c':
    friendly_name: Light Living Wall Right 3
  '0x001788010ee67439':
    friendly_name: Light Living Thermostat
  '0x804b50fffebd0a11':
    friendly_name: Light Hall 0 Wall
  '0x187a3efffef7819e':
    friendly_name: Light Bathroom
  '0x54ef4410004dc729':
    friendly_name: Plug Garden Lights
  '0x0015bc002f00e6f5':
    friendly_name: Plug Entertainment
  '0x54ef4410003134b1':
    friendly_name: Plug Dryer
  '0x9035eafffe5f9085':
    friendly_name: Plug Washing Machine
  '0x001788010b233f45':
    friendly_name: Light Dining Table
  '0x9035eafffe5f8d28':
    friendly_name: Plug Quooker and Dishwasher
  '0x54ef4410002c99b3':
    friendly_name: Plug Workstation
  '0x54ef441000d2c5eb':
    friendly_name: Water Leak Washing Machine
  '0x00158d008bbe4928':
    friendly_name: Water Leak Dryer
  '0x00158d008bbf75b3':
    friendly_name: Water Leak Quooker
  '0x00158d0008980cd7':
    friendly_name: Climate Bedroom Olivier
  '0x00158d0007ef3720':
    friendly_name: Climate Bedroom Duco
  '0x00158d000838465a':
    friendly_name: Climate Bedroom JC
  '0x00158d0007f82b0b':
    friendly_name: Climate Living
  '0x00158d0008328d5e':
    friendly_name: Climate Bathroom
  '0x00158d0007f82928':
    friendly_name: Climate Study
  '0x00158d0008912748':
    friendly_name: Door Living Stair Cabinet
  '0x00158d00091ead1d':
    friendly_name: Climate Fridge
  '0x00158d0008328d33':
    friendly_name: Climate Storage
  '0x00158d008bbe4913':
    friendly_name: Water Leak Dishwasher
  '0x001788010c24ce62':
    friendly_name: Switch Dimmer Bathroom
  '0x001788010eed6730':
    friendly_name: Light Living Wall Left 3
  '0x001788010e438b31':
    friendly_name: Light Kitchen Middle 2
  '0x001788010e43e39a':
    friendly_name: Light Kitchen Middle 3
  '0x001788010e438c3e':
    friendly_name: Light Kitchen Middle 4
  '0x001788010e43e358':
    friendly_name: Light Kitchen Countertop 1
  '0x001788010e43e385':
    friendly_name: Light Kitchen Countertop 2
  '0x001788010eee17e5':
    friendly_name: Light Stair Cabinet
  '0x001788010ef1af8a':
    friendly_name: Light Bedroom Duco 4
  '0x001788010eed58f2':
    friendly_name: Light Bedroom Duco 1
  '0x001788010eef9259':
    friendly_name: Light Bedroom Duco 3
  '0x001788010eef928d':
    friendly_name: Light Bedroom Olivier 6
  '0x001788010ef1af85':
    friendly_name: Light Bedroom Olivier 5
  '0x001788010eed6b09':
    friendly_name: Light Bedroom Olivier 1
  '0x001788010ee80a35':
    friendly_name: Light Bedroom Olivier 2
  '0x001788010eef9276':
    friendly_name: Light Bedroom Olivier 3
  '0x001788010e43e179':
    friendly_name: Light Bedroom Olivier 4
  '0x001788010d348233':
    friendly_name: Switch Tap Dial Bedroom Duco
  '0x001788010d3460ef':
    friendly_name: Switch Tap Dial Bedroom Olivier
  '0x001788010cc472c2':
    friendly_name: Switch Wall Bedroom Duco
  '0x001788010cc472cb':
    friendly_name: Switch Wall Bedroom Olivier
  '0x001788010cc472a6':
    friendly_name: Switch Wall Kitchen
  '0x001788010cc47291':
    friendly_name: Switch Wall Toilet
  '0x001788010cc472e5':
    friendly_name: Switch Wall Living
  '0x001788010ee67448':
    friendly_name: Light Toilet
  '0x0017880104f42a11':
    friendly_name: Switch Dimmer Bedroom JC Bed C
  '0x001788010871a0c5':
    friendly_name: Switch Dimmer Bedroom JC Bed J
  '0x001788010eed6adf':
    friendly_name: Light Living Wall Left 2
  '0x001788010eed6db0':
    friendly_name: Light Living Wall Left 1
  '0x001788010eed5e3b':
    friendly_name: Light Bedroom Duco 2
  '0x001788010efd454a':
    friendly_name: Light Go
    availability: false
groups:
  '1':
    friendly_name: Light Group Living Spot
  '2':
    friendly_name: Light Group Hall 0 Spot
  '3':
    friendly_name: Light Group Kitchen Middle
  '4':
    friendly_name: Light Group Kitchen Countertop
  '5':
    friendly_name: Light Group Bedroom Duco Ambiance
  '6':
    friendly_name: Light Group Bedroom Olivier Ambiance
  '7':
    friendly_name: Light Group Bedroom Duco Color
  '8':
    friendly_name: Light Group Living Spot Dark Outside
  '9':
    friendly_name: Light Group Living Spot Always
  '10':
    friendly_name: Light Group Bedroom Olivier Color
  '11':
    friendly_name: Light Group Bedroom Olivier
  '12':
    friendly_name: Light Group Bedroom Duco
