homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1884
availability:
  enabled: true
serial:
  adapter: zstack
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_23_90_DB_6C-if00-port0
frontend:
  enabled: true
  port: 8080
advanced:
  channel: 25
  pan_id: 35539
  network_key: '!secret.yaml network_key'
  log_level: debug
device_options: {}
version: 4
devices:
  '0x0000000001732f4d':
    friendly_name: Switch Hall 0
  '0x001788010d12f602':
    friendly_name: Switch Living Tap Dial
  '0x0017880104f4f2b7':
    friendly_name: Switch Living Dimmer
  '0x001788010eee44ec':
    friendly_name: Light Hall 0 1
  '0x001788010ee66c15':
    friendly_name: Light Hall 0 2
  '0x001788010eee5b84':
    friendly_name: Light Hall 0 3
  '0x001788010ee656be':
    friendly_name: Light Hall 0 4
  '0x001788010eee1582':
    friendly_name: Light Living Entrance
  '0x84fd27fffe3b11f1':
    friendly_name: Light Living White Cabinet
  '0x001788010ee66d40':
    friendly_name: Light Living Wall Left 1
  '0x001788010ee652c5':
    friendly_name: Light Living Wall Left 2
  '0x001788010ee652ae':
    friendly_name: Light Living Wall Left 3
  '0x001788010ee64599':
    friendly_name: Light Living Garden L1
  '0x001788010ee66ab7':
    friendly_name: Light Living Garden L2
  '0x001788010ee621ee':
    friendly_name: Light Living Garden R1
  '0x001788010ee621f5':
    friendly_name: Light Living Garden R2
  '0x001788010eee58e0':
    friendly_name: Light Living Wall Right 1
  '0x001788010eee39bb':
    friendly_name: Light Living Wall Right 2
  '0x001788010eee567c':
    friendly_name: Light Living Wall Right 3
  '0x001788010ee67439':
    friendly_name: Light Living Thermostat
  '0x804b50fffebd0a11':
    friendly_name: Light Hall 0 Wall
  '0x187a3efffef7819e':
    friendly_name: Light Bathroom
  '0x54ef4410004dc729':
    friendly_name: Plug Garden Lights
  '0x0015bc002f00e6f5':
    friendly_name: Plug Entertainment
  '0x54ef4410003134b1':
    friendly_name: Plug Dryer
  '0x9035eafffe5f9085':
    friendly_name: Plug Washing Machine
  '0x001788010b233f45':
    friendly_name: Light Dining Table
  '0x9035eafffe5f8d28':
    friendly_name: Plug Quooker and Dishwasher
  '0x54ef4410002c99b3':
    friendly_name: Plug Workstation
  '0x54ef441000d2c5eb':
    friendly_name: Water Leak Washing Machine
  '0x00158d008bbe4928':
    friendly_name: Water Leak Dryer
  '0x00158d008bbf75b3':
    friendly_name: Water Leak Quooker
  '0x00158d008bbe3d84':
    friendly_name: Water Leak Dishwasher
  '0x00158d0008980cd7':
    friendly_name: Climate Bedroom Olivier
  '0x00158d0007ef3720':
    friendly_name: Climate Bedroom Duco
  '0x00158d000838465a':
    friendly_name: Climate Bedroom JC
  '0x00158d0007f82b0b':
    friendly_name: Climate Living
  '0x00158d0008328d5e':
    friendly_name: Climate Bathroom
  '0x00158d0007f82928':
    friendly_name: Climate Study
  '0x00158d0008912748':
    friendly_name: Door Living Stair Cabinet
  '0x00158d00091ead1d':
    friendly_name: Climate Fridge
  '0x00158d0008328d33':
    friendly_name: Climate Storage
  '0x0017880108d1b3f3':
    friendly_name: Light Stair Cabinet
  '0x00158d008bbe4913':
    friendly_name: Water Leak Storage Room Window
groups:
  '1':
    friendly_name: Light Group Living Spot
  '2':
    friendly_name: Light Group Hall 0 Spot
