blueprint:
  name: Soil Humidity too low
  description: Alert when a plant needs water.
  domain: automation
  input:
    plant_name:
      name: Plant name
      description: Human readable plant name
    humidity_entity:
      name: Humidity sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    humidity_threshold_entity:
      name: Humidity threshold
      description: Alert when humidity gets below this value.
      selector:
        entity:
          domain: input_number

mode: restart

trigger:
  platform: numeric_state
  below: !input humidity_threshold_entity
  entity_id: !input humidity_entity
  for: "01:00:00"

variables:
  plant_name: !input plant_name
  humidity_entity: !input humidity_entity
  humidity_threshold_entity: !input humidity_threshold_entity

action:
  - service: notify.notify
    #  - service: notify.mobile_app_J12P
    data:
      title: "{{ plant_name }}"
      message: "Need water, Humidity is {{ states(humidity_entity) }} % and threshold is {{ states(humidity_threshold_entity) }} %"
