blueprint:
  name: Soil Moisture too low
  description: Alert when a plant needs water.
  domain: automation
  input:
    plant_name:
      name: Plant name
      description: Human readable plant name
    instruction:
      name: Instruction
      description: Additional watering instruction
    moisture_entity:
      name: Moisture sensor
      selector:
        entity:
          domain: sensor
          device_class: moisture
    moisture_threshold_entity:
      name: Moisture threshold
      description: Alert when moisture gets below this value.
      selector:
        entity:
          domain: input_number

mode: restart

trigger:
  platform: numeric_state
  below: !input moisture_threshold_entity
  entity_id: !input moisture_entity
  for: "01:00:00"

variables:
  plant_name: !input plant_name
  moisture_entity: !input moisture_entity
  moisture_threshold_entity: !input moisture_threshold_entity
  instruction: !input instruction


action:
  - service: notify.notify
    #- service: notify.mobile_app_JX
    data:
      title: "{{ plant_name }} heeft dorst"
      message: >-
        Vochtigheid {{ states(moisture_entity)|round }}% (grens is {{ states(moisture_threshold_entity)|round }})%.
        {{ instruction }}
