- alias: Fridge temp above threshold
  id: fridge-temp-above-11
  trigger:
    - platform: numeric_state
      entity_id: sensor.climate_fridge_temperature
      above: input_number.fridge_temperature_threshold
  action:
    - service: notify.mobile_app_j16
      data:
        title: 🌡️ Fridge
        message: >-
          Fridge temperature is high!
          Measured {{ states('sensor.climate_fridge_temperature') | round(1) }}°C
        data:
          clickAction: /dashboard-power/appliances
          actions:
            - action: "URI"
              title: "Open Appliances"
              uri: "/dashboard-power/appliances"
  mode: single
