- alias: Fridge temp above 8 degrees
  id: fridge-temp-above-11
  trigger:
    - platform: numeric_state
      entity_id: sensor.climate_fridge_temperature
      above: 8
  action:
    - service: notify.mobile_app_j16
      data:
        title: Fridge
        message: >-
          Fridge temperature is high.
          Measured {{ states('sensor.climate_fridge_temperature') | round(1) }}°C
        data:
          url: /dashboard-power/appliances
  mode: single
