- alias: Heating study on when working
  id: heating-study-on-when-working
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_workstation_power
      above: 60
  condition:
    - condition: time
      before: &off_time "21:00:00"
    - condition: state
      entity_id: sensor.at_least_one_person_home
      state: "yes"
  action:
    - service: climate.set_temperature
      data:
        temperature: &target_temp 20
      target:
        entity_id: climate.study
    - variables:
        study_target_temp: *target_temp
        bedroom_jc_initial_temp: "{{ state_attr('climate.bedroom_jc', 'current_temperature') }}"
        bedroom_jc_target_temp: "{{ bedroom_jc_initial_temp | float(target_temp) + 1.0 }}"
    - choose:
      # If living room is not heating much (anymore), use Bedroom JC thermostat to activate heating.
      # (Study thermostat does not do that since it's just a smart radiator valve).
      # There are no radiators in Bedroom JC, so need to manually turn it off when the temp has been reached.
      - conditions:
          - condition: numeric_state
            entity_id: sensor.living_heating
            below: 10  # percent
        sequence:
          - action: climate.set_temperature
            data:
              temperature: "{{ bedroom_jc_target_temp }}"
            target:
              entity_id: climate.bedroom_jc
          - alias: "Wait for study to reach target temp"
            wait_template: "{{ state_attr('climate_study', 'current_temperature') >= target_temp }}"
            timeout: "01:00:00"
          - action: climate.set_temperature
            data:
              temperature: "{{ bedroom_jc_initial_temp }}"
            target:
              entity_id: climate.bedroom_jc
  mode: restart

- alias: Heating study off
  id: heating-study-off
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_workstation_power
      below: 55
      for: "00:10:00"
    - platform: time
      at: *off_time
  action:
    - service: climate.set_temperature
      data:
        temperature: 16
      target:
        entity_id: climate.study
  mode: restart
