- alias: Heating study on when working
  id: heating-study-on-when-working
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_workstation_power
      above: 60
    - condition: state
      entity_id: sensor.at_least_one_person_home
      state: "yes"
  condition:
    - condition: time
      before: &off_time "21:00:00"
  action:
    - service: climate.set_temperature
      data:
        temperature: 20
      target:
        entity_id: climate.study
  mode: restart

- alias: Heating study off
  id: heating-study-off
  trigger:
    - platform: numeric_state
      entity_id: sensor.plug_workstation_power
      below: 55
      for: "00:10:00"
    - platform: time
      at: *off_time
  action:
    - service: climate.set_temperature
      data:
        temperature: 16
      target:
        entity_id: climate.study
  mode: restart
