- alias: Light Disco Olivier
  id: light-disco-olivier
  use_blueprint:
    path: custom/light_disco.yaml
    input:
      light_group_color: &light_olivier_color light.light_group_bedroom_olivier_color
      input_boolean_disco: &bool_olivier input_boolean.disco_olivier

- alias: Light Disco Olivier Off
  id: light-disco-olivier-off
  trigger:
    - platform: state
      entity_id: *light_olivier_color
      to: "off"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: *bool_olivier
  mode: restart
