- alias: "Light Bedroom JC Bed J evening on"
  id: light-bedroom-jc-bed-j-evening-on
  use_blueprint:
    path: custom/light_turn_on_at_time.yaml
    input:
      person_entity: person.jori
      light_entity: light.light_bedroom_jc_bed_j
      time: "21:00:00"

- alias: "Light Bedroom JC Bed C evening on"
  id: light-bedroom-jc-bed-c-evening-on
  use_blueprint:
    path: custom/light_turn_on_at_time.yaml
    input:
      person_entity: person.chantal
      light_entity: light.light_bedroom_jc_bed_c
      time: "21:00:00"

- alias: "Light Bedroom JC Bed J midnight off"
  id: light-bedroom-jc-bed-j-midnight-off
  use_blueprint:
    path: custom/light_turn_off_at_time.yaml
    input:
      person_entity: person.jori
      light_entity: light.light_bedroom_jc_bed_j
      time: "00:00:00"
      transition: 10

- alias: "Light Bedroom JC Bed C midnight off"
  id: light-bedroom-jc-bed-c-midnight-off
  use_blueprint:
    path: custom/light_turn_off_at_time.yaml
    input:
      person_entity: person.chantal
      light_entity: light.light_bedroom_jc_bed_c
      time: "00:00:00"
      transition: 10
