- alias: "Adaptive light: toggle"
  id: "adaptive-light-toggle"
  trigger:
    - platform: state
      entity_id: input_boolean.adaptive_lighting
    - platform: homeassistant
      event: start  # in case the states aren't properly restored
  variables:
    new_state: "{{ states('input_boolean.adaptive_lighting') }}"
  action:
    - service: "switch.turn_{{ new_state }}"
      entity_id:
        - switch.adaptive_lighting_living_spot
        - switch.adaptive_lighting_hall_0
        - switch.adaptive_lighting_dining_table
