- alias: Central heating cabinet light on/off
  id: central-heating-cabinet-light-on-off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_central_heating_contact
      to:
        - 'on'
        - 'off'
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.light_group_central_heating
  mode: restart
