- alias: Garden lights on
  id: garden-lights-on
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      to: "on"
    - platform: state
      entity_id: binary_sensor.presence_ground_floor
      from: "off"
      to: "on"
    # Attempt to turn on lights when only one of us arrives home:
    - platform: state
      entity_id: person.jori
      from: away
      to: home
    - platform: state
      entity_id: person.chantal
      from: away
      to: home
  condition:
    - condition: state
      entity_id: binary_sensor.presence_house
      state: "on"
    - condition: state
      entity_id: binary_sensor.dark_outside
      state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights off
  id: garden-lights-off
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      to: "off"
    - platform: state
      entity_id: binary_sensor.presence_ground_floor
      to: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_garden_lights
  mode: restart
