# Automations to turn on lights when something happens nearby

- alias: Proximity-activated light living white cabinet
  id: proximity-activated-light-living-white-cabinet
  trigger:
    - platform: state
      entity_id: &living_spot light.light_group_living_spot
      to:
        - "on"
        - "off"
  # variables:
    # proxy_light_entity: *living_spot
    # proxy_light_state: "{{ states(proxy_light_entity) }}"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.light_living_white_cabinet
  mode: restart
