- alias: Garden lights on at sunset
  id: garden-lights-on-sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights off at 23 or sunrise
  id: garden-lights-off-23-or-sunrise
  trigger:
    - platform: time
      at: "23:00:00"
    - platform: sun
      event: sunrise
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

# If lights in the living room turn on in the morning, _and_ if it's before sunrise,
# turn on the garden lights as well.
- alias: Garden lights on in the morning
  id: garden-lights-on-in-the-morning
  trigger:
    - platform: state
      entity_id: light.light_group_living_spot
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
      before: "09:00:00"
    - condition: sun
      before: sunrise
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart
