# Requires input boolean

- alias: Light Disco Duco
  id: light-disco-duco
  use_blueprint:
    path: custom/light_disco.yaml
    input:
      light_group_color: light.light_group_bedroom_duco_color
      input_boolean_disco: input_boolean.disco_duco

- alias: Light Disco Olivier
  id: light-disco-olivier
  use_blueprint:
    path: custom/light_disco.yaml
    input:
      light_group_color: light.light_group_bedroom_olivier_color
      input_boolean_disco: input_boolean.disco_olivier
