- alias: Garden lights on at sunset
  id: garden-lights-on-sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights off at 23
  id: garden-lights-off-23
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

