- alias: Stair cabinet light on/off
  id: stair-cabinet-light-on-off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_living_stair_cabinet_contact
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_living_stair_cabinet_contact
      to: 'off'
  action:
    - service: >-
        {% if is_state('binary_sensor.door_living_stair_cabinet_contact', 'on') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      target:
        entity_id: light.light_stair_cabinet
