- alias: Garden lights on at sunset
  id: garden-lights-on-sunset
  trigger:
    - platform: sun
      event: sunset
  # Not much point in turning it on if no one's home. But there is another automation to turn it on if someone comes
  # home later.
  condition:
    - condition: state
      entity_id: sensor.at_least_one_person_home
      state: "yes"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights off at bedtime or sunrise
  id: garden-lights-off-bedtime-or-sunrise
  trigger:
    - platform: time
      at: &bedtime "23:00:00"
    - platform: sun
      event: sunrise
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights on in evening after arrival
  id: garden-lights-on-in-evening-after-arrival
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home
      from: "no"
      to: "yes"
  condition:
    - condition: sun
      after: sunset
    - condition: time
      before: *bedtime
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

- alias: Garden lights on briefly at night after arrival
  id: garden-lights-on-briefly-at-night-after-arrival
  trigger:
    - platform: state
      entity_id: person.jori
      from: away
      to: home
    - platform: state
      entity_id: person.chantal
      from: away
      to: home
  condition:
    - condition: time
      after: *bedtime
    - condition: sun
      before: sunset
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
    - delay:
        minutes: 15
    - service: switch.turn_off
      target:
        entity_id: switch.plug_garden_lights
  mode: restart

# If lights in the living room turn on in the morning, _and_ if it's before sunrise,
# turn on the garden lights as well.
- alias: Garden lights on in the morning
  id: garden-lights-on-in-the-morning
  trigger:
    - platform: state
      entity_id: light.light_group_living_spot
      to: "on"
  condition:
    - condition: time
      after: "05:00:00"
      before: "09:00:00"
    - condition: sun
      before: sunrise
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_garden_lights
  mode: restart
