- alias: Stair cabinet light on/off
  id: stair-cabinet-light-on-off
  trigger:
    - platform: state
      entity_id: binary_sensor.door_living_stair_cabinet_contact
      to:
        - 'on'
        - 'off'
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.light_stair_cabinet
  mode: restart
