- alias: Set motion detected recently
  id: set-motion-detected-recently
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_kitchen_occupancy
        - binary_sensor.motion_toilet_occupancy
        - binary_sensor.motion_hall_0_occupancy
        - binary_sensor.door_living_stair_cabinet_contact
      to: "on"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.motion_detected_recently
    - service: timer.start
      data:
        entity_id: timer.motion_detected_recently
  mode: restart

- alias: Clear motion detected recently
  id: clear-motion-detected-recently
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.motion_detected_recently
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.motion_detected_recently
  mode: single
