- alias: Switch Bathroom Dimmer
  id: switch-bathroom-dimmer
  description: ""
  use_blueprint:
    path: custom/hue_dimmer_switch_v2.yaml
    input:
      mqtt_topic: zigbee2mqtt/Switch Bathroom Dimmer
      helper_last_controller_event: input_text.switch_bathroom_dimmer_helper
      on_press_release:
        - action: light.turn_on
          target:
            entity_id:
              - light.light_bathroom
      off_press_release:
        - action: light.turn_off
          target:
            entity_id:
              - light.light_bathroom
      up_press:
        - action: light.turn_on
          data:
            brightness_step_pct: 5
            transition: 1
          target:
            entity_id:
              - light.light_bathroom
      up_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: 5
            transition: 1
          target:
            entity_id:
              - light.light_bathroom
      down_press:
        - action: light.turn_on
          data:
            brightness_step_pct: -5
            transition: 1
          target:
            entity_id:
              - light.light_bathroom
      down_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: -5
            transition: 1
          target:
            entity_id:
              - light.light_bathroom
