- alias: Switch Wall Bedroom Duco New
  id: switch_wall_bedroom_duco_new
  use_blueprint:
    path: custom/hue_wall_switch_dim.yaml
    input:
      controller: Switch Wall Bedroom Duco New
      left_light:
        - light.light_group_bedroom_duco_new
      left_dim_direction_entity: input_text.dim_direction_switch_wall_bedroom_duco_new_left
