
- alias: Switch Wall Living
  id: switch_wall_living
  use_blueprint:
    path: custom/hue_wall_switch_dim.yaml
    input:
      controller: Switch Wall Living
      left_light:
        - light.light_dining_table
      left_dim_direction_entity: input_text.dim_direction_switch_wall_living_left
      right_light:
        - light.light_group_living_spot_always
        - light.light_group_living_spot_dark_outside
      right_dim_direction_entity: input_text.dim_direction_switch_wall_living_right
      right_condition_entity: binary_sensor.sufficiently_dark_for_indoor_lights
      right_light_alt:
        - light.light_group_living_spot_always

- alias: Switch Tap Dial Living
  id: switch_tap_dial_living
  use_blueprint:
    path: custom/hue_tap_dial.yaml
    input:
      controller: Switch Tap Dial Living
      button_1_press: &ref_turn_on
        - service: "light.turn_on"
          data:
            transition: 1
          target:
            entity_id:
              - light.light_dining_table
              - light.light_group_living_spot_always
        - choose:
            - conditions:
                - condition: state
                  entity_id: binary_sensor.sufficiently_dark_for_indoor_lights
                  state: "on"
              sequence:
                - service: "light.turn_on"
                  data:
                    transition: 1
                  target:
                    entity_id:
                      - light.light_group_living_spot_dark_outside
      button_3_press: &ref_turn_off
        - action: light.turn_off
          target:
            entity_id:
              - light.light_dining_table
              - light.light_group_living_spot_always
              - light.light_group_living_spot_dark_outside
      button_4_press:
        - action: input_boolean.toggle
          target:
            entity_id: input_boolean.sleep_mode
      brightness_step_down: &ref_brightness_down
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            # TODO add spots
            entity_id: light.light_dining_table
      brightness_step_up: &ref_brightness_up
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            # TODO add spots
            entity_id: light.light_dining_table

- alias: Switch Dimmer Living
  id: switch-dimmer-living
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Living
      on_press: *ref_turn_on
      off_press: *ref_turn_off
      up_press_or_hold: *ref_brightness_up
      down_press_or_hold: *ref_brightness_down
