- alias: Swich Living Tap Dial
  id: switch_living_tap_dial
  use_blueprint:
    path: custom/hue_tap_dial.yaml
    input:
      mqtt_topic: zigbee2mqtt/Switch Living Tap Dial
      remote_button_1_single_press:
        - action: scene.turn_on
          metadata: {}
          data:
            transition: 1
          target:
            entity_id: scene.living_daytime
      remote_button_3_single_press:
        - action: scene.turn_on
          metadata: {}
          data:
            transition: 1
          target:
            entity_id: scene.living_off
      remote_button_2_single_press:
        - action: scene.turn_on
          metadata: {}
          data:
            transition: 1
          target:
            entity_id: scene.living_evening
      remote_dial_rotate_left_step:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            entity_id: light.light_group_living
      remote_dial_rotate_left_slow:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            entity_id: light.light_group_living
      remote_dial_rotate_left_fast:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: -20
          target:
            entity_id: light.light_group_living
      remote_dial_rotate_right_step:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: light.light_group_living
      remote_dial_rotate_right_slow:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: light.light_group_living
      remote_dial_rotate_right_fast:
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: 20
          target:
            entity_id: light.light_group_living
