- alias: Switch Dimmer Bathroom
  id: switch-dimmer-bathroom
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Bathroom
      on_press:
        - action: light.turn_on
          target:
            entity_id: &ref_lights
              - light.light_bathroom
      off_press:
        - action: light.turn_off
          target:
            entity_id: *ref_lights
      up_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: 10
            transition: 1
          target:
            entity_id: *ref_lights
      down_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: -10
            transition: 1
          target:
            entity_id: *ref_lights
