- alias: Switch Dimmer Bedroom JC Bed C
  id: switch-dimme-bedroom-jc-bed-c
  description: ""
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Bedroom JC Bed C
      on_press:
        - action: light.turn_on
          target:
            entity_id: &ref_c light.light_bedroom_jc_bed_c
      off_press:
        - action: light.turn_off
          target:
            entity_id: *ref_c
      up_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step: &brightness_step 25
            transition: 1
          target:
            entity_id: *ref_c
      down_press_or_hold:
        - variables:
            light_entity: *ref_c
            brightness_step: *brightness_step
            current_brightness: "{{ state_attr(light_entity, 'brightness') }}"
        - service: light.turn_on
          data:
            transition: 1
            brightness: "{{ max(current_brightness - brightness_step, 1) }}"
          target:
            entity_id: *ref_c

- alias: Switch Dimmer Bedroom JC Bed J
  id: switch-dimme-bedroom-jc-bed-j
  description: ""
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Bedroom JC Bed J
      on_press:
        - action: light.turn_on
          target:
            entity_id: &ref_j light.light_bedroom_jc_bed_j
      off_press:
        - action: light.turn_off
          target:
            entity_id: *ref_j
      up_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step: *brightness_step
            transition: 1
          target:
            entity_id: *ref_j
      down_press_or_hold:
        - variables:
            light_entity: *ref_j
            brightness_step: *brightness_step
            current_brightness: "{{ state_attr(light_entity, 'brightness') }}"
        - service: light.turn_on
          data:
            transition: 1
            brightness: "{{ max(current_brightness - brightness_step, 1) }}"
          target:
            entity_id: *ref_j
