
- alias: Switch Wall Living
  id: switch_wall_living
  use_blueprint:
    path: custom/hue_wall_switch.yaml
    input:
      controller: Switch Wall Living
      left_press:
        - action: light.toggle
          target:
            entity_id: light.light_dining_table
      right_press:
        - action: light.toggle
          target:
            entity_id:
              - light.light_group_living_spot
              - light.light_living_white_cabinet

- alias: Switch Tap Dial Living
  id: switch_tap_dial_living
  use_blueprint:
    path: custom/hue_tap_dial.yaml
    input:
      controller: Switch Tap Dial Living
      button_1_press:
        - action: light.turn_on
          target:
            entity_id: &ref_floor_0_living_area
              - light.light_group_living_spot
              - light.light_living_white_cabinet
              - light.light_dining_table
              - light.light_group_kitchen_middle
              - light.light_group_kitchen_countertop
      button_3_press:
        - action: light.turn_off
          target:
            entity_id: *ref_floor_0_living_area
      button_4_press:
        - action: input_boolean.toggle
          target:
            entity_id: input_boolean.sleep_mode
      brightness_step_down:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            # Don't dim the cabinet, not needed:
            entity_id: &ref_floor_0_living_area_excl_cabinet
              - light.light_group_living_spot
              - light.light_dining_table
              - light.light_group_kitchen_middle
              - light.light_group_kitchen_countertop
      brightness_step_up:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: *ref_floor_0_living_area_excl_cabinet

- alias: Switch Dimmer Living
  id: switch-dimmer-living
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Living
      on_press:
        - action: light.turn_on
          target:
            entity_id: *ref_floor_0_living_area
      off_press:
        - action: light.turn_off
          target:
            entity_id: *ref_floor_0_living_area
      up_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: 20
            transition: 1
          target:
            # Don't dim the cabinet, not needed:
            entity_id: *ref_floor_0_living_area_excl_cabinet
      down_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step_pct: -20
            transition: 1
          target:
            entity_id: *ref_floor_0_living_area_excl_cabinet
