- alias: Switch Wall Kitchen
  id: switch_wall_kitchen
  use_blueprint:
    path: custom/hue_wall_switch.yaml
    input:
      controller: Switch Wall Kitchen
      left_press:
        - action: light.toggle
          target:
            entity_id: &ref_lights
              - light.light_group_kitchen_middle
              - light.light_group_kitchen.countertop
