- alias: Switch Tap Dial Laundry
  id: switch_tap_dial_laundry
  use_blueprint:
    path: custom/hue_tap_dial_adaptive_lighting.yaml
    input:
      controller: Switch Tap Dial Laundry
      brightness_max: 125
      brightness_step: 10
      light_group_all: light.light_group_laundry
      switch_entities_adaptive_lighting:
        - switch.adaptive_lighting_laundry
      switch_entities_adapt_brightness:
        - switch.adaptive_lighting_adapt_brightness_laundry

- alias: Switch Wall Laundry
  id: switch_wall_laundry
  use_blueprint:
    path: custom/hue_wall_switch_dim.yaml
    input:
      controller: Switch Wall Laundry
      left_light:
        - light.light_group_laundry
      left_dim_direction_entity: input_text.dim_direction_switch_wall_laundry_left
