- alias: Switch Dimmer Bathroom
  id: switch-dimmer-bathroom
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Bathroom
      on_press:
        - action: light.turn_on
          target:
            entity_id: &light_entity light.light_bathroom
      off_press:
        - action: light.turn_off
          target:
            entity_id: *light_entity
      up_press_or_hold:
        - action: light.turn_on
          data:
            brightness_step: &brightness_step 25
            transition: 1
          target:
            entity_id: *light_entity
      down_press_or_hold:
        - variables:
            light_entity: *light_entity
            brightness_step: *brightness_step
            current_brightness: "{{ state_attr(light_entity, 'brightness') }}"
        - service: light.turn_on
          data:
            transition: 1
            brightness: "{{ max(current_brightness - brightness_step, 1) }}"
          target:
            entity_id: *light_entity
