- alias: Switch Wall Kitchen
  id: switch_wall_kitchen
  trigger:
    platform: state
    entity_id: sensor.switch_wall_kitchen_action
    to: 'left_press'
  action:
    - service: light.toggle
      target:
        entity_id:
          - light.light_group_kitchen_middle
          - light.light_group_kitchen.countertop
  mode: single
