
- alias: Switch Wall Living
  id: switch_wall_living
  use_blueprint:
    path: custom/hue_wall_switch.yaml
    input:
      controller: Switch Wall Living
      left_press:
        - action: light.toggle
          target:
            entity_id: light.light_dining_table
      right_press:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.low_illuminance_outside
                    state: "on"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id:
                        - light.light_group_living_spot_dark_outside
                        - light.light_group_living_spot_always
            default:
              - service: light.toggle
                target:
                  entity_id: light.light_group_living_spot_always

- alias: Switch Tap Dial Living
  id: switch_tap_dial_living
  use_blueprint:
    path: custom/hue_tap_dial.yaml
    input:
      controller: Switch Tap Dial Living
      button_1_press: &ref_turn_on
        - service: "light.turn_on"
          data:
            transition: 1
          target:
            entity_id:
              - light.light_dining_table
              - light.light_group_living_spot_always
        - choose:
            - conditions:
                - condition: state
                  entity_id: binary_sensor.low_illuminance_outside
                  state: "on"
              sequence:
                - service: "light.turn_on"
                  data:
                    transition: 1
                  target:
                    entity_id:
                      - light.light_group_living_spot_dark_outside
      button_3_press: &ref_turn_off
        - action: light.turn_off
          target:
            entity_id:
              - light.light_dining_table
              - light.light_group_living_spot_always
              - light.light_group_living_spot_dark_outside
      button_4_press:
        - action: input_boolean.toggle
          target:
            entity_id: input_boolean.sleep_mode
      brightness_step_down: &ref_brightness_down
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            # TODO add spots
            entity_id: light.light_dining_table
      brightness_step_up: &ref_brightness_up
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            # TODO add spots
            entity_id: light.light_dining_table

- alias: Switch Dimmer Living
  id: switch-dimmer-living
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Dimmer Living
      on_press: *ref_turn_on
      off_press: *ref_turn_off
      up_press_or_hold: *ref_brightness_up
      down_press_or_hold: *ref_brightness_down
