- alias: Swich Living Tap Dial
  id: switch_living_tap_dial
  use_blueprint:
    path: custom/hue_tap_dial.yaml
    input:
      mqtt_topic: zigbee2mqtt/Switch Living Tap Dial
      remote_button_1_single_press:
        - action: light.turn_on
          target:
            entity_id: &ref_floor_0_living_area
              - light.light_group_living_spot
              - light.light_living_white_cabinet
              - light.light_dining_table
              - light.light_group_kitchen_middle
              - light.light_group_kitchen_countertop
      remote_button_3_single_press:
        - action: light.turn_off
          target:
            entity_id: *ref_floor_0_living_area
      remote_button_4_single_press:
        - action: input_boolean.toggle
          target:
            entity_id: input_boolean.sleep_mode
      remote_dial_rotate_left_step:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            entity_id: &ref_dim_not_cabinet
              - light.light_group_living_spot
              - light.light_dining_table
              - light.light_group_kitchen_middle
              - light.light_group_kitchen_countertop
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -5
          target:
            entity_id: &ref_cabinet
              - light.light_living_white_cabinet
      remote_dial_rotate_left_slow:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            entity_id: *ref_dim_not_cabinet
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -5
          target:
            entity_id: *ref_cabinet
      remote_dial_rotate_left_fast:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -20
          target:
            entity_id: *ref_dim_not_cabinet
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: -10
          target:
            entity_id: *ref_cabinet
      remote_dial_rotate_right_step:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: *ref_dim_not_cabinet
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 5
          target:
            entity_id: *ref_cabinet
      remote_dial_rotate_right_slow:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: *ref_dim_not_cabinet
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 5
          target:
            entity_id: *ref_cabinet
      remote_dial_rotate_right_fast:
        - action: light.turn_on
          data:
            transition: 1
            brightness_step_pct: 20
          target:
            entity_id: *ref_dim_not_cabinet
        - action: light.turn_on
          metadata: {}
          data:
            transition: 1
            brightness_step_pct: 10
          target:
            entity_id: *ref_cabinet
