- alias: Living Dimmer Switch
  id: living-dimmer-switch
  description: ""
  use_blueprint:
    path: custom/hue_dimmer_switch.yaml
    input:
      controller: Switch Living Dimmer
      on_released:
        - action: light.turn_on
          target:
            entity_id: &ref_all
              - light.light_group_hall_0_spot
              - light.light_hall_0_wall
              - light.light_group_living_spot
              - light.light_living_white_cabinet
              - light.light_dining_table
      off_released:
        - action: light.turn_off
          target:
            entity_id: *ref_all
      up_held:
        - action: light.turn_on
          data:
            brightness_step_pct: 20
            transition: 1
          target:
            entity_id: &ref_dim_20
              - light.light_group_living_spot
              - light.light_dining_table
        - action: light.turn_on
          data:
            brightness_step_pct: 10
            transition: 1
          target:
            entity_id: &ref_dim_10
              - light.light_living_white_cabinet
      down_held:
        - action: light.turn_on
          data:
            brightness_step_pct: -20
            transition: 1
          target:
            entity_id: *ref_dim_20
        - action: light.turn_on
          data:
            brightness_step_pct: -10
            transition: 1
          target:
            entity_id: *ref_dim_10
