permit_join: true
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1884
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
device_options:
  legacy: false
