permit_join: false
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1884
availability: true
serial:
  port: tcp://192.168.2.35:6638
  baudrate: 115200
  disable_led: false
frontend:
  port: 8080
advanced:
  transmit_power: 20
  channel: 25
  pan_id: 19243
  network_key: '!secret.yaml network_key'
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: debug
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x54ef4410003134b1':
    friendly_name: Plug Dryer
  '0x9035eafffe5f8d28':
    friendly_name: Plug Dishwasher
  '0x54ef4410002c8e06':
    friendly_name: Plug Roomba
  '0x54ef4410002c99b3':
    friendly_name: Plug Workstation
  '0x0015bc002f00e6f5':
    friendly_name: Plug Entertainment
  '0x00158d0007ef3720':
    friendly_name: Climate Bedroom Duco
  '0x00158d0007f82928':
    friendly_name: Climate Study
  '0x001788010d344736':
    friendly_name: '0x001788010d344736'
  '0x0017880108b473c4':
    friendly_name: '0x0017880108b473c4'
  '0x00158d000838465a':
    friendly_name: Climate Bedroom JC
  '0x00158d0008328d5e':
    friendly_name: Climate Bathroom
  '0x00158d0008980cd7':
    friendly_name: Climate Bedroom Olivier
  '0x00158d0008328d33':
    friendly_name: Climate Laundry
  '0x54ef4410004e474a':
    friendly_name: Motion Toilet 0
  '0x001788010ba4b8dd':
    friendly_name: '0x001788010ba4b8dd'
  '0x001788010baaaab7':
    friendly_name: '0x001788010baaaab7'
  '0x001788010bf7528b':
    friendly_name: '0x001788010bf7528b'
  '0x001788010bf73aab':
    friendly_name: '0x001788010bf73aab'
  '0x0015bc001a022855':
    friendly_name: Motion Dressing
  '0x001788010b99b7d9':
    friendly_name: '0x001788010b99b7d9'
  '0x001788010b96e6f3':
    friendly_name: '0x001788010b96e6f3'
  '0x001788010b8090f3':
    friendly_name: '0x001788010b8090f3'
  '0x001788010bf78479':
    friendly_name: '0x001788010bf78479'
  '0x001788010b809cae':
    friendly_name: '0x001788010b809cae'
  '0x54ef4410004dbaa3':
    friendly_name: Plug Garden Lights
  '0x04cd15fffed20dfe':
    friendly_name: Light Storage Range Extender
  '0x001788010b9bc267':
    friendly_name: Light Dressing
  '0x001788010b962adc':
    friendly_name: Light Toilet 0
  '0x001788010cc47291':
    friendly_name: Switch Toilet 0
  '0x001788010cc472d2':
    friendly_name: Switch Dressing
  '0x0017880100de56e3':
    friendly_name: Light Storage Range Extender 3
  '0x00158d00091ead1d':
    friendly_name: Climate SolarEdge
  '0xa4c138e50b8266d1':
    friendly_name: Soil Vrouwentong
  '0xa4c1387a936c28f7':
    friendly_name: Soil Calathea
  '0xa4c138e44f6f21a7':
    friendly_name: Soil Outside
  '0xa4c138951089df55':
    friendly_name: Soil Drakenbloedboom
  '0xa4c138b1aa9af402':
    friendly_name: Soil Koraalcactus
  '0x54ef4410004dc729':
    friendly_name: Plug Floor Heating Pump
  '0x9035eafffe5f9085':
    friendly_name: Plug Washing Machine
  '0xf0d1b8be2409045a':
    friendly_name: Plug Outdoor Christmas Lights
  '0xa4c1389d0325ace4':
    friendly_name: Soil Ginseng
  '0xa4c138499137d23c':
    friendly_name: Soil Monstera
  '0xa4c13856658db029':
    friendly_name: Soil Dwergpalm
  '0xa4c13809f5c260be':
    friendly_name: Soil Treurvijg
  '0x00158d000911ddbb':
    friendly_name: Door Bathroom
  '0x00158d0007f82b0b':
    friendly_name: Climate Living Room
  '0xa4c138631f04a21d':
    friendly_name: Plug Veranda Lights
  '0x0017880100dbc8a0':
    friendly_name: Light Veranda Wall
  '0x0015bc002f00e692':
    friendly_name: Plug Boiler
blocklist:
  - '0xec1bbdfffe7f3c18'
  - '0x001788010c690db7'
  - '0x001788010c5c2da3'
