- platform: template
  sensors:
    at_least_one_person_home:
      # Think I need to convert to https://www.home-assistant.io/integrations/template/#binary-sensor
      # icon: mdi:home-map-marker
      friendly_name: At Least One Person Home
      value_template: >-
        {% if states('person.jori') == "home" or
              states('person.chantal') == "home" or
              states('input_boolean.motion_detected_recently') == "on" or
              states('sensor.plug_workstation_power') | float(0) > 60 or
              states('sensor.plug_entertainment_power') | float(0) > 30
        %}
          yes
        {% else %}
          no
        {% endif %}
