adaptive_lighting:
  name: Adaptive Lighting
  icon: mdi:theme-light-dark

sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep
sleep_mode_kids:
  name: Sleep Mode Kids
  icon: mdi:sleep

disco_olivier:
  name: Disco Olivier
  icon: mdi:party-popper
  initial: false
disco_living:
  name: Disco Living
  icon: mdi:party-popper
  initial: false

wake_up_light_kids_enabled:
  name: Wake Up Light Kids Enabled
  icon: mdi:alarm-check
  initial: true

wake_up_lights_kids_cycle_in_progress:
  name: Wake Up Lights Kids Cycle In Progress
  icon: mdi:alarm-note
  initial: false

window_heat_ground_floor_close_sent:
  name: Window Heat Ground Floor Close Sent
window_heat_ground_floor_open_sent:
  name: Window Heat Ground Floor Open Sent
window_heat_first_floor_close_sent:
  name: Window Heat First Floor Close Sent
window_heat_first_floor_open_sent:
  name: Window Heat First Floor Open Sent
window_heat_second_floor_close_sent:
  name: Window Heat Second Floor Close Sent
window_heat_second_floor_open_sent:
  name: Window Heat Second Floor Open Sent
