adaptive_lighting:
  name: Adaptive Lighting
  icon: mdi:theme-light-dark

sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep
sleep_mode_kids:
  name: Sleep Mode Kids
  icon: mdi:sleep

disco_olivier:
  name: Disco Olivier
  icon: mdi:party-popper
  initial: false
disco_living:
  name: Disco Living
  icon: mdi:party-popper
  initial: false

wake_up_light_kids_enabled:
  name: Wake Up Light Kids Enabled
  icon: mdi:alarm-check
  initial: true

wake_up_lights_kids_cycle_in_progress:
  name: Wake Up Lights Kids Cycle In Progress
  icon: mdi:alarm-note
  initial: false

window_alert_active:
  name: Window Alert Active
  icon: mdi:window-closed-variant
  initial: false

window_close_alerted_ground:
  name: Window Close Alerted Ground Floor
  icon: mdi:window-closed
  initial: false

window_close_alerted_first:
  name: Window Close Alerted First Floor
  icon: mdi:window-closed
  initial: false

window_close_alerted_second:
  name: Window Close Alerted Second Floor
  icon: mdi:window-closed
  initial: false

window_open_alerted_ground:
  name: Window Open Alerted Ground Floor
  icon: mdi:window-open
  initial: false

window_open_alerted_first:
  name: Window Open Alerted First Floor
  icon: mdi:window-open
  initial: false

window_open_alerted_second:
  name: Window Open Alerted Second Floor
  icon: mdi:window-open
  initial: false
