- platform: group
  name: "Light Group Hall 0"
  entities:
    - light.light_hall_0_1
    - light.light_hall_0_2
    - light.light_hall_0_3
    - light.light_hall_0_4
    - light.light_hall_0_wall
- platform: group
  name: "Light Group Living Spot"
  entities:
    - light.light_living_entrance
    - light.light_living_wall_left_1
    - light.light_living_wall_left_2
    - light.light_living_wall_left_3
    - light.light_living_garden_l1
    - light.light_living_garden_l2
    - light.light_living_garden_r1
    - light.light_living_garden_r2
    - light.light_living_wall_right_1
    - light.light_living_wall_right_2
    - light.light_living_wall_right_3
    - light.light_living_thermostat
