# https://www.home-assistant.io/dashboards/dashboards/#adding-more-dashboards-with-yaml
mode: yaml
dashboards:
  dashboard-generated:
    mode: yaml
    filename: notexist.yaml
    title: Generated
    icon: mdi:tools
    show_in_sidebar: true
    require_admin: true
  dashboard-overview:
    mode: yaml
    filename: dashboard/overview.yaml
    title: Overview (custom)
    icon: mdi:view-dashboard
    show_in_sidebar: true
  dashboard-climate:
    mode: yaml
    filename: dashboard/climate.yaml
    title: Climate
    icon: mdi:thermometer
    show_in_sidebar: true
  dashboard-lights:
    mode: yaml
    filename: dashboard/lights.yaml
    title: Lights
    icon: mdi:globe-light
    show_in_sidebar: true
  dashboard-power:
    mode: yaml
    filename: dashboard/power.yaml
    title: Power
    icon: mdi:alpha-w
    show_in_sidebar: true
