- name: Hall 0 daytime 
  entities:
    light.light_group_hall_0:
      state: "on"
      color_temp_kelvin: 4000
      brightness: 100

- name: Hall 0 evening
  entities:
    light.light_group_hall_0:
      state: "on"
      color_temp_kelvin: 2500
      brightness: 100

- name: Hall 0 off
  entities:
    light.light_group_hall_0:
      state: "off"

- name: Living daytime
  entities:
    light.light_group_living:
      state: "on"
      color_temp_kelvin: 4000
      brightness: 100

- name: Living evening
  entities:
    light.light_group_living:
      state: "on"
      color_temp_kelvin: 2500
      brightness: 100

- name: Living off
  entities:
    light.light_group_living:
      state: "off"

