version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1100
      - PGID=1100
      - MEM_LIMIT=1024 #optional
      # - MEM_STARTUP=1024 #optional
    volumes:
      - ./config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      # - 1900:1900/udp #optional
      # 1900 UDP is needed for "Make controller discoverable on L2 network" option.
      # Seems to be for SSDP - Simple service discovery protocol.
      # The port is in use by Home Assistant, and we don't use this option anyway in Unifi
      # settings. It does mean that the Unifi controller itself isn't discoverable in Home 
      # Assistant, but we can just add the integration manually.
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
