version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:7.5.174
    container_name: unifi-network-application
    depends_on: 
      - unifi-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      #- MEM_STARTUP=1024 #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 1900:1900/udp #optional
      # 1900 UDP is needed for "Make controller discoverable on L2 network" option.
      # Seems to be for SSDP - Simple service discovery protocol.
      # The port is in use by Home Assistant, and we don't use this option anyway in Unifi
      # settings. It does mean that the Unifi controller itself isn't discoverable in Home 
      # Assistant, but we can just add the integration manually.
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  unifi-db:
    # Formally only mongodb 3.6 through 4.4 are supported, however, it has been reported that newer versions will work.
    # 4.4 requires ARMv8.2-A or higher, 4.3 doesn't exist?
    # applies to all versions ≥5.0, any of 4.4 ≥4.4.19, and any of 4.2 ≥4.2.19
    image: mongo:4.2.18
    container_name: unifi-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

