- alias: Bathroom Heating on
  id: bathroom-heating-on
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home
      to: "yes"
    - platform: time
      at: '07:00:00'
    - platform: state
      entity_id: binary_sensor.door_bathroom_contact
      to: "off"  # off = door closed, weirdly
    - platform: numeric_state
      entity_id: sensor.climate_bathroom_temperature
      below: 19.8  # TODO input number
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.at_least_one_person_home
        state: "yes"
      - condition: time
        after: "07:00"
        before: "22:00"
      - condition: state
        entity_id: binary_sensor.door_bathroom_contact
        state: "off"
      - condition: numeric_state
        entity_id: sensor.climate_bathroom_temperature
        below: 19.8  # TODO input number
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_bathroom_heater


- alias: Bathroom Heating off
  id: bathroom-heating-off
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home
      to: "no"
      for: "00:01:00"
    - platform: time
      at: '23:00:00'
    - platform: state
      entity_id: binary_sensor.door_bathroom_contact
      to: "on"  # means door is open
      for: "00:01:00"
    - platform: numeric_state
      entity_id: sensor.climate_bathroom_temperature
      above: 20 # TODO input number
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_bathroom_heater
