- alias: Boiler off when last person leaves
  id: boiler-off-away
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home 
      from: 'yes'
      to: 'no'
      for: '00:30:00'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_boiler
  mode: restart

- alias: Boiler on when someone comes home
  id: boiler-on-return
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home 
      from: 'no'
      to: 'yes'
      for: '00:00:05'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_boiler
  mode: restart
