- alias: Boiler off when last person leaves
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home 
      from: 'yes'
      to: 'no'
      for: '00:30:00'
  condition:
    - condition: state
      entity_id: switch.plug_boiler
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_boiler
  mode: restart


- alias: Boiler on when someone comes home
  trigger:
    - platform: state
      entity_id: sensor.at_least_one_person_home 
      from: 'no'
      to: 'yes'
      for: '00:00:05'
  condition:
    - condition: state
      entity_id: switch.plug_boiler
      state: 'off'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_boiler
  mode: restart
