- alias: Alert dishwasher done
  id: 'alert-dishwasher-done'
  trigger:
    - platform: state 
      entity_id: sensor.dishwasher_state
      from: 'drying'
      to: 'washing'  # not quite, pumping out water, but we don't have a state for that
      for: '00:00:30'
  action:
    - wait_for_trigger:
      - platform:  state
        entity_id: sensor.dishwasher_state
        to: 'off_closed'
        for: '00:00:30'
      timeout: '00:05:00'
      continue_on_timeout: false
    - service: notify.notify
      data:
        title: Dishwasher
        message: Done
  mode: restart

