- id: doorbell
  alias: Notify Doorbell
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    from: 'off'
    to: 'on'
  action:
    - service: notify.notify
      data:
        title: Deurbel gaat
        data:
          push:
            sound: "doorbell-ding-dong.wav"
        message: Er belt iemand aan
    - service: shell_command.front_camera_snap
    - service: shell_command.front_camera_crop
    - service: notify.notify
      data:
        title: Deurbel foto
        # N.b.: actually in /media, local is imaginary
        data:
          image: "/media/local/front-snap-cropped.jpeg"
        message: Foto
    # when flashing, with hue, light doesn't actually change state
    - service: light.turn_on
      target:
        entity_id:
          - light.hue_light_group_living
          - light.hue_light_group_study
      data:
        flash: short

