- alias: "Floor Heating Pump toggle"
  id: floor-heating-pump-toggle
  trigger:
    - platform: template
      alias: "Temp rose sufficiently to turn off"
      value_template: >-
        {{ states('sensor.climate_living_room_temperature') | float(100) >
           (states('input_number.living_room_temperature_target') | float(0) +
            states('input_number.living_room_temperature_pump_offset') | float(0) +
            states('input_number.living_room_temperature_pump_margin') | float(0)
           )
        }}
    - platform: template
      alias: "Temp dropped sufficiently to turn on"
      value_template: >-
        {{ states('sensor.climate_living_room_temperature') | float(0) <
           (states('input_number.living_room_temperature_target') | float(0) +
            states('input_number.living_room_temperature_pump_offset') | float(0) -
            states('input_number.living_room_temperature_pump_margin') | float(0)
           )
        }}
    # Fallback trigger, consider removing if there is sufficient comfort that temp-based triggers
    # do the job.
    # Used by to be every minute, but it led to a lot of spam in the Logbook.
    - platform: time_pattern
      hours: 1
    - platform: homeassistant
      event: start
  variables:
    target_plus_offset: >-
      {{ states('input_number.living_room_temperature_target') | float(19) +
         states('input_number.living_room_temperature_pump_offset') | float(0)
      }}
    margin: >-
      {{ states('input_number.living_room_temperature_pump_margin') | float(0) }}
    # The default of 0 makes the pump always go on if the sensor is dead, which is useful to
    # ensure continuation of service:
    temp: >-
      {{ states('sensor.climate_living_room_temperature') | float(0) }}
    turn_on_below: "{{ target_plus_offset - margin }}"
    turn_off_above: "{{ target_plus_offset + margin }}"
    desired_state: >-
      {{ "on" if (temp | float(0)) < (turn_on_below | float(0)) else
         "off" if (temp | float(0)) > (turn_off_above | float(0)) else
         "undefined"
      }}
  action:
    #    - service: notify.mobile_app_JX
    #      data:
    #        title: Debug FHP toggle
    #        message: >
    #          target_plus_offset: {{ target_plus_offset }},
    #          margin: {{ margin }},
    #          temp: {{ temp }},
    #          turn_on_below: {{ turn_on_below }},
    #          turn_off_below: {{ turn_off_below }},
    #          desired_state: {{ desired_state }}
    - choose:
      - conditions:
          condition: template
          value_template: >-
            {{ desired_state != 'undefined' and
               desired_state != states('switch.plug_floor_heating_pump')
            }}
        sequence:
          - service: "switch.turn_{{ desired_state }}"
            target:
              entity_id: switch.plug_floor_heating_pump
  mode: restart

# Run pump for 30 mins daily at night outside of the heating season,
# intended to keep the water flowing regularly.
- alias: "Floor Heating Pump Nightly Flush"
  id: floor-heating-pump-nightly-flush
  trigger:
    - platform: time
      at: '03:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.plug_floor_heating_pump
        state: "off"
      # Proxy for "not in heating season":
      - condition: numeric_state
        entity_id: sensor.climate_living_room_temperature
        above: 22
  action:
    - service: automation.turn_off
      entity_id: automation.floor_heating_pump_toggle
    - service: switch.turn_on
      target:
        entity_id: switch.plug_floor_heating_pump
    - delay: '00:30:00'
    - service: switch.turn_off
      target:
        entity_id: switch.plug_floor_heating_pump
    - service: automation.turn_on
      entity_id: automation.floor_heating_pump_toggle
  mode: restart

- alias: "Alert Floor Heating Pump toggle possibly compromised"
  id: alert-floor-heating-pump-toggle
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.plug_floor_heating_pump
          state: "off"
        # Use this temp sensor in case Aqara sensor lost connection
        - condition: numeric_state
          entity_id: sensor.motion_hall_0_temperature
          below: 19
  action:
    - service: notify.notify
      data:
        title: Floor Heating Pump
        message: Expected to be on, but is off
  mode: restart
