- alias: Garden lights on
  id: 'garden-lights-on'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30"
  # TODO: also trigger if someone comes home after sundown but before 22:00
  condition:
    - condition: state
      entity_id: sensor.at_least_one_person_home
      state: true
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.garden_lights
  mode: restart

- alias: Garden lights off
  id: 'garden-lights-off'
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.garden_lights
  mode: restart
