- alias: "Housekeeping mode: scheduled on"
  id: housekeeping-scheduled-on
  trigger:
  - platform: time
    at: "11:55:00"
  condition:
    - condition: time
      weekday:
        - mon
    # Only even weeknumbers:
    - condition: template
      value_template: "{{ (as_timestamp(now())|timestamp_custom ('%W') | int % 2) == 0 }}"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.housekeeping_mode
  mode: restart

- alias: "Housekeeping mode: scheduled off"
  id: housekeeping-scheduled-off
  trigger:
  - platform: time
    at: "16:15:00"
  condition:
    - condition: time
      weekday:
        - mon
    # Only even weeknumbers:
    - condition: template
      value_template: "{{ (as_timestamp(now())|timestamp_custom ('%W') | int % 2) == 0 }}"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.housekeeping_mode
  mode: restart

- alias: "Housekeeping Mode: turn on"
  id: "housekeeping-mode-turn-on"
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeping_mode
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.motion_activated_lights
        - input_boolean.adaptive_lighting
    - service: light.turn_on
      entity_id:
        # exclude bedrooms to prevent waking someone accidentally
        - light.hue_light_group_living
        - light.hue_light_group_kitchen
        - light.hue_light_group_study
        - light.light_bathroom
        - light.light_hall_0
        - light.light_hall_1
        - light.light_hall_2
        - light.light_laundry
        - light.light_dressing
        - light.light_walk_in_closet
        - light.light_toilet_0
        - light.light_toilet_1
      data:
        brightness: 255
        kelvin: 4000

- alias: "Housekeeping Mode: turn off"
  id: "housekeeping-mode-turn-off"
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeping_mode
      to: 'off'
  action:
    # Turning everything off assumes it's still daylight, which would usually be the case.
    # Except perhaps deep winter. We'll see in winter '23-'24.
    - service: light.turn_off
      entity_id:
        - light.hue_light_group_living
        - light.hue_light_group_kitchen
        - light.hue_light_group_study
        - light.light_bathroom
        - light.light_hall_0
        - light.light_hall_1
        - light.light_hall_2
        - light.light_laundry
        - light.light_dressing
        - light.light_walk_in_closet
        - light.light_toilet_0
        - light.light_toilet_1
    # short delay appears to be needed to prevent adaptive light from immediately turning lights on again
    - delay: "00:00:01"
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.motion_activated_lights
        - input_boolean.adaptive_lighting


