- alias: "Housekeeping Mode: turn on"
  id: "housekeeping-mode-turn-on"
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeping_mode
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.motion_activated_lights
        - input_boolean.adaptive_lighting
    - service: light.turn_on
      entity_id:
        # exclude bedrooms to prevent waking someone accidentally
        - light.hue_light_group_living
        - light.hue_light_group_kitchen
        - light.hue_light_group_study
        - light.light_bathroom
        - light.light_hall_0
        - light.light_hall_1
        - light.light_hall_2
        - light.light_laundry
        - light.light_dressing
        - light.light_walk_in_closet
        - light.light_toilet_0
        - light.light_toilet_1
      data:
        brightness: 255
        kelvin: 4000

- alias: "Housekeeping Mode: turn off"
  id: "housekeeping-mode-turn-off"
  trigger:
    - platform: state
      entity_id: input_boolean.housekeeping_mode
      to: 'off'
  action:
    # This kinda assumes daylight, which would usually be the case.
    - service: light.turn_off
      entity_id:
        - light.hue_light_group_living
        - light.hue_light_group_kitchen
        - light.hue_light_group_study
        - light.light_bathroom
        - light.light_hall_0
        - light.light_hall_1
        - light.light_hall_2
        - light.light_laundry
        - light.light_dressing
        - light.light_walk_in_closet
        - light.light_toilet_0
        - light.light_toilet_1
    # short delay appears to be needed to prevent adaptive light from immediately turning lights on again
    - delay: "00:00:01"
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.motion_activated_lights
        - input_boolean.adaptive_lighting

