- alias: Veranda lights on at sunset
  id: veranda-lights-on-sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
    - platform: state
      entity_id: sensor.at_least_one_person_home
      from: "no"
      to: "yes"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: state
        entity_id: sensor.at_least_one_person_home
        state: "yes"
      - condition: time
        before: "23:00:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_veranda_lights
  mode: restart

- alias: Veranda lights off at 23
  id: veranda-lights-off-23
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_veranda_lights
  mode: restart
