- alias: Outdoor Christmas lights on at sunset
  id: outdoor-christmas-lights-on-sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_outdoor_christmas_lights
  mode: restart

- alias: Outdoor Christmas lights off at midnight
  id: outdoor-christmas-lights-off-midnight
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_outdoor_christmas_lights
  mode: restart

- alias: Outdoor Christmas lights on at 6
  id: outdoor-christmas-lights-on-6
  trigger:
    - platform: time
      at: "06:00:00"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_outdoor_christmas_lights
  mode: restart

- alias: Outdoor Christmas lights off at sunrise
  id: outdoor-christmas-lights-off-sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_outdoor_christmas_lights
  mode: restart
