- alias: "Sleep mode: scheduled on"
  id: al-sleep-on
  trigger:
  - platform: time
    at: "23:00:00"
  action:
    # if someone is in the bathroom, don't put them in the dark:
    - wait_template: '{{ states("light.light_bathroom") != "on" }}'
      continue_on_timeout: 'true'
      timeout: '00:30:00'  # it can't take longer than this, right?
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: scheduled off - daycare days"
  id: al-sleep-off-daycare
  trigger:
  - platform: time
    at: "07:00:00"
  condition:
  - condition: time
    weekday:
      - mon
      - thu
      - fri
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: scheduled off - non-daycare days"
  id: al-sleep-off-non-daycare
  trigger:
  - platform: time
    at: "08:00:00"
  condition:
  - condition: time
    weekday:
      - tue
      - wed
      - sat
      - sun
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: toggle"
  id: "sleep-toggle"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
    - platform: homeassistant
      event: start  # in case the states aren't properly restored
  variables:
    sleep_mode: "{{ states('input_boolean.sleep_mode') }}"
  action:
    - service: "switch.turn_{{ sleep_mode }}"
      entity_id:
        - switch.adaptive_lighting_sleep_mode_motion
        - switch.adaptive_lighting_sleep_mode_motion_hall_0
        - switch.adaptive_lighting_sleep_mode_motion_floor_1
        - switch.adaptive_lighting_sleep_mode_motion_bathroom
    # Nest Protect pathlight is sufficient.
    - service: "automation.turn_{{ 'off' if sleep_mode == 'on' else 'on' }}"
      entity_id: automation.motion_activated_light_hall_1
