- alias: Study lights on at sunset when working
  id: study-lights-on-sunset-when-working
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  condition:
    - condition: and
      conditions:
        - alias: "Workstation plug on as proxy for working"
          condition: state
          entity_id: switch.plug_workstation
          state: "on"
        # "on" isn't sufficient: I could have just left, relying on the 30-min idle turn-off
        - alias: "Ensure power draw"
          condition: numeric_state
          entity_id: sensor.plug_workstation_power
          above: 20
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_study
      data:
        # TODO: enroll into adaptive lightning, then remove brightness/color
        brightness: 180
        color_temp: 280
        transition: 30
  mode: restart

# - alias: Living room lights on when not at home (dimmed)

# - alias: Living room lights on when at home (bright)

# - alias: Living room lights to bright when coming home after sunset
# (but before off time)

# - alias: Living room lights off evening
# 00:00 Fri & Sat, 23:00 other days?

# - alias: Lights off at sunset
# Exclude all:
# * motion activated lights
# * bedrooms
# * dining table lights IF someone is home
