- alias: Switch Light Toilet 1
  id: switch-toilet-1
  trigger:
    platform: state
    entity_id: sensor.switch_toilet_1_action
    to: 'left_press'
  action:
    - service: light.toggle
      target:
        entity_id: light.light_toilet_1
  mode: single

- alias: Switch Light Hall 1 Downstairs Left Press
  id: switch-hall-1-downstairs-left-press
  trigger:
    platform: state
    entity_id: sensor.switch_hall_1_downstairs_action
    to: 'left_press'
  action:
    - service: light.toggle
      target:
        entity_id: light.light_hall_1
  mode: single

- alias: Switch Light Hall 1 Downstairs Right Press
  id: switch-hall-1-downstairs-right-press
  trigger:
    platform: state
    entity_id: sensor.switch_hall_1_downstairs_action
    to: 'right_press'
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.sleep_mode
  mode: single

- alias: Switch Light Hall 1 Upstairs Left Press
  id: switch-hall-1-upstairs-left-press
  trigger:
    platform: state
    entity_id: sensor.switch_hall_1_upstairs_action
    to: 'left_press'
  action:
    - service: light.toggle
      target:
        entity_id: light.light_hall_1
  mode: single

- alias: Switch Light Hall 1 Upstairs Right Press
  id: switch-hall-1-upstairs-right-press
  trigger:
    platform: state
    entity_id: sensor.switch_hall_1_upstairs_action
    to: 'right_press'
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.sleep_mode
  mode: single
