- alias: Proximity-activated Light Study - on
  id: pal-study-on
  description: "There isn't a dedicated motion sensor here, but lighting up this area when someone is nearby is pretty useful."
  trigger:
    - platform: state
      entity_id:
        - light.light_walk_in_closet
        - light.light_hall_2
      to: 'on'
  condition:
    condition: and
    conditions:
      # Can't check light groups here because they can't go "unavailable" if power is cut to the
      # entire group. They stay "on" if they were on before.
      # In this case, only checking 1 light is sufficient because they are always toggled together.
      - condition: state
        entity_id: light.light_study_spot_center
        state:
          - 'off'
          - 'unavailable'
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_study
      data:
        brightness: "{{ states('input_number.proximity_activated_light_study_brightness') | int }}"
        color_temp: 370
  mode: restart

- alias: Proximity-activated Light Study - off
  id: pal-study-off
  description: "Turn the study lights off again, unless the brightness was changed."
  trigger:
    - platform: state
      entity_id:
        - light.light_walk_in_closet
        - light.light_hall_2
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - light.light_walk_in_closet
          - light.light_hall_2
        state: 'off'
      - condition: template
        value_template: '{{state_attr(''light.hue_light_group_study'', ''brightness'') | int(0) == states("input_number.proximity_activated_light_study_brightness") | int }}'
  action:
    - service: light.turn_off
      target:
        entity_id: light.hue_light_group_study
  mode: restart

- alias: Proximity-activated Light Living + Kitchen - on
  id: pal-living-kitchen-on
  description: "There isn't a dedicated motion sensor here, but lighting up this area when someone is nearby is pretty useful."
  trigger:
    # Trigger on motion sensor state rather than light state, because this light has soft-off
    - platform: state
      entity_id: binary_sensor.motion_hall_0_occupancy
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - light.light_arc
          - light.light_flower
          - light.light_dining_kitchen_side
        state:
          - 'off'
          - 'unavailable'
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_kitchen
      data:
        brightness: '{{ states("input_number.proximity_activated_light_kitchen_brightness") | int }}'
        color_temp: 455  # 2200k
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_living
      data:
        brightness: '{{ states("input_number.proximity_activated_light_living_brightness") | int }}'
        color_temp: 455
  mode: restart

- alias: Proximity-activated Light Living + Kitchen - off
  id: pal-living-kitchen-off
  description: "Turn the living room + kitchen lights off again, unless they were changed manually."
  trigger:
    - platform: state
      entity_id: light.light_hall_0
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ state_attr(''light.hue_light_group_kitchen'', ''brightness'') | int(0) == states("input_number.proximity_activated_light_kitchen_brightness") | int }}'
      - condition: template
        value_template: '{{state_attr(''light.hue_light_group_living'', ''brightness'') | int(0) == states("input_number.proximity_activated_light_living_brightness") | int }}'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.hue_light_group_kitchen
          - light.hue_light_group_living
  mode: restart

- alias: Proximity-activated Light Bathroom - on
  id: pal-bathroom-on
  description: >-
    Light up the bathroom just slightly when there is motion in the hallway, so that it is
    not completely dark when you walk in.
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hall_1_occupancy
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.light_bathroom
        state: "off"
      - condition: state
        entity_id: input_boolean.sleep_mode
        state: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_motion_bathroom
    - service: light.turn_on
      target:
        entity_id:
          - light.light_bathroom
      data:
        brightness: 50
  mode: restart

- alias: Proximity-activated Light Bathroom - off
  id: pal-bathroom-off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hall_1_occupancy
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.light_bathroom
        state: "on"
      - condition: state
        entity_id: binary_sensor.motion_bathroom_occupancy
        state: "off"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.light_bathroom
    # Might need a delay here, could reset off transition
    - service: switch.turn_on
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_motion_bathroom
  mode: restart

- alias: Proximity-activated Light Bathroom - re-enable adaptive on motion
  id: pal-bathroom-re-enable-adaptive-motion
  description: >-
    Adaptive light brightness gets disabled when it starts on proximity activation, in order to get a low
    brightness. Turn it back on when motion is detected.
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_bathroom_occupancy
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_motion_bathroom
    - condition: "state"
      entity_id: switch.adaptive_lighting_motion_bathroom
      state: "on"
    - service: light.turn_on
      target:
        entity_id: light.light_bathroom
      # Have to set brightness manually, just light.turn_on is not sufficient
      data:
        brightness: '{{ state_attr("switch.adaptive_lighting_motion_bathroom", "brightness_pct") / 100 * 255 }}'
