- alias: Motion-activated Light Hall 1
  id: mal-hall-1
  use_blueprint:
    path: custom/motion_light_lux_aware.yaml
    input:
      motion_entity: sensor.motion_stairs_or_hall_1_occupancy
      lux_entity: sensor.motion_hall_1_illuminance_lux
      device_no_motion_wait: sensor.motion_stairs_or_hall_1_occupancy_timeout
      light_target:
        entity_id: light.light_hall_1

- alias: Motion-activated Light Hall 2
  id: mal-hall-2
  use_blueprint:
    path: custom/motion_light_lux_aware.yaml
    input:
      motion_entity: sensor.motion_stairs_1_or_hall_2_occupancy
      lux_entity: sensor.motion_hall_2_illuminance_lux
      device_no_motion_wait: sensor.motion_stairs_1_or_hall_2_occupancy_timeout
      light_target:
        entity_id: light.light_hall_2

- alias: Motion-activated Light Walk-in Closet
  id: mal-walk-in-closet
  use_blueprint:
    path: custom/motion_light_lux_aware.yaml
    input:
      motion_entity: binary_sensor.motion_walk_in_closet_occupancy
      lux_entity: sensor.motion_walk_in_closet_illuminance_lux
      device_no_motion_wait: number.motion_walk_in_closet_occupancy_timeout
      light_target:
        entity_id: light.light_walk_in_closet

- alias: Motion-activated Light Laundry
  id: mal-laundry
  use_blueprint:
    path: custom/motion_light_lux_aware.yaml
    input:
      motion_entity: binary_sensor.motion_laundry_occupancy
      lux_entity: sensor.motion_laundry_illuminance_lux
      device_no_motion_wait: number.motion_laundry_occupancy_timeout
      light_target:
        entity_id: light.light_laundry

- alias: Motion-activated Light Toilet 1
  id: mal-toilet-1
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_toilet_1_occupancy
      light_target:
        entity_id: light.light_toilet_1
      no_motion_wait: "{{ max(420 - states('number.motion_toilet_1_detection_interval') | int(0), 0) }}"

# The Bathroom light does not use any blueprint, because it also activates on proximity using hall 1.
# This makes the unconditional turn_off to not work well: it will go off while there still is motion in hall 1.
# Instead, if should go to low light level.
- alias: Motion-activated Light Bathroom
  id: mal-bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.motion_bathroom_occupancy
    from: "off"
    to: "on"
  action:
    - alias: "Turn on the light"
      service: light.turn_on
      target:
        entity_id: light.light_bathroom
    - alias: "Wait until there is no motion from device"
      wait_for_trigger:
        platform: state
        entity_id: binary_sensor.motion_bathroom_occupancy
        from: "on"
        to: "off"
    - alias: "Wait the number of seconds that has been set"
      # 180s on device, add 120s for 5 min in total
      # N.b.: this was originally reduced to just 180s when sleep mode is on, consider putting that back in.
      delay: 120
    - choose:
      - conditions:
        - condition: state
          entity_id: binary_sensor.motion_hall_1_occupancy
          state: "on"
        sequence:
          - alias: "Set light to low brightness because there is still motion in the hallway"
            service: light.turn_on
            target:
              entity_id: light.light_bathroom
            data:
              brightness: 50
              transition: 10
      default:
        - alias: "Turn off the light"
          service: light.turn_off
          target:
            entity_id: light.light_bathroom
          data:
            transition: 10
  mode: restart
  max_exceeded: silent

- alias: "Motion-activated Lights: toggle"
  id: "motion-activated-lights-toggle"
  trigger:
    - platform: state
      entity_id: input_boolean.motion_activated_lights
    - platform: homeassistant
      event: start  # in case the states aren't properly restored
  variables:
    mal: "{{ states('input_boolean.motion_activated_lights') }}"
  action:
    - service: "automation.turn_{{ mal }}"
      entity_id:
        # If hall 1 is toggled off manually, it will turn on again when this boolean changes state
        # (e.g. in the morning).
        # May want to make this more sophisticated, but usually it shouldn't be a problem.
        - automation.motion_activated_light_hall_1
        - automation.motion_activated_light_hall_2
        - automation.motion_activated_light_laundry
        - automation.motion_activated_light_toilet_1
        - automation.motion_activated_light_walk_in_closet
        - automation.motion_activated_light_bathroom
        - automation.proximity_activated_light_living_kitchen_off
        - automation.proximity_activated_light_living_kitchen_on
        - automation.proximity_activated_light_study_off
        - automation.proximity_activated_light_study_on
        - automation.proximity_activated_light_bathroom_off
        - automation.proximity_activated_light_bathroom_on
        - automation.proximity_activated_light_bathroom_re_enable_adaptive_on_motion
