- alias: Motion-activated Light Hall 0
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_hall_0_occupancy
      light_target:
        entity_id: light.light_hall_0
      no_motion_wait: 180

- alias: Motion-activated Light Hall 1
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_hall_1_occupancy
      light_target:
        entity_id: light.light_hall_1

- alias: Motion-activated Light Hall 2
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_hall_2_occupancy
      light_target:
        entity_id: light.light_hall_2

- alias: Motion-activated Light Dressing
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_dressing_occupancy
      light_target:
        entity_id: light.light_dressing
      no_motion_wait: 60

- alias: Motion-activated Light Walk-in Closet
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_walk_in_closet_occupancy
      light_target:
        entity_id: light.light_walk_in_closet

- alias: Motion-activated Light Laundry
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_laundry_occupancy
      light_target:
        entity_id: light.light_laundry

- alias: Motion-activated Light Toilet 0
  use_blueprint:
#    path: homeassistant/motion_light_custom_long_off_transition.yaml
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_toilet_0_occupancy
      light_target:
        entity_id: light.light_toilet_0
      no_motion_wait: 300

- alias: Motion-activated Light Toilet 1
  use_blueprint:
#    path: homeassistant/motion_light_custom_long_off_transition.yaml
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_toilet_1_occupancy
      light_target:
        entity_id: light.light_toilet_1
      no_motion_wait: 300

# Ikea bulbs at 1% are still too bright unfortunately. And Nest Protect pathlight is sufficient.
- alias: Motion-activated Light Hall 1 - off at Night
  trigger:
  - platform: time
    at: "21:59:55"
  action:
    - service: automation.turn_off
      entity_id: automation.motion_activated_light_hall_1_3
    - service: light.turn_off
      target:
        entity_id: light.light_hall_1

- alias: Motion-activated Light Hall 1 - on in Morning daycare days
  trigger:
  - platform: time
    at: "07:00:05"
  condition:
  - condition: time
    weekday:
      - mon
      - thu
      - fri
  action:
    - service: automation.turn_on
      entity_id: automation.motion_activated_light_hall_1_3

- alias: Motion-activated Light Hall 1 - on in Morning non-daycare days
  trigger:
  - platform: time
    at: "08:00:05"
  condition:
  - condition: time
    weekday:
      - tue
      - wed
      - sat
      - sun
  action:
    - service: automation.turn_on
      entity_id: automation.motion_activated_light_hall_1_3

