- alias: "Plug off after 30 min idle - Entertainment"
  id: entertainment-off
  trigger:
    - platform: state
      entity_id: sensor.entertainment_state 
      from: 'on'
      to: 'off'
      for: '00:30:00'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_entertainment
  mode: restart

- alias: "Plug off after 30 min idle - Workstation"
  id: workstation-off
  trigger:
    - platform: state
      entity_id: sensor.workstation_state 
      from: 'on'
      to: 'off'
      for: '00:30:00'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_workstation
  mode: restart

- alias: "Plug off after 2h idle - Roomba"
  id: roomba-idle-auto-off
  trigger:
    - platform: state
      entity_id: sensor.roomba_state
      from: 'on'
      to: 'off'
      for: '02:00:00'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_roomba
  mode: restart

