- alias: Alert inverter hot
  id: alert-inverter-hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.climate_solaredge_temperature
      above: 30
      for: '01:00:00'
    - platform: numeric_state
      entity_id: sensor.climate_solaredge_temperature
      above: 40
      for: '01:00:00'
    - platform: numeric_state
      entity_id: sensor.climate_solaredge_temperature
      above: 50
      for: '01:00:00'
    - platform: numeric_state
      entity_id: sensor.climate_solaredge_temperature
      above: 60
      for: '01:00:00'
  action:
    - service: notify.notify
      data:
        title: Attic inverter temperature
        message: >
          The ambient temperature around the SolarEdge inverter on the attic is above {{ sensor.climate_solaredge_temperature }} °C degrees.
  mode: restart

- alias: Alert phase over 23A
  id: alert-phase-over-23-a
  trigger:
    - platform: numeric_state
      entity_id: sensor.electricity_meter_current_phase_l1
      above: 23
    - platform: numeric_state
      entity_id: sensor.electricity_meter_current_phase_l2
      above: 23
    - platform: numeric_state
      entity_id: sensor.electricity_meter_current_phase_l3
      above: 23
  action:
    - service: notify.mobile_app_JX
      data:
        title: Electricity overload warning
        message: >
          One of the phases is over 23A.
          L1: {{ states('sensor.electricity_meter_current_phase_l1') }}A,
          L2: {{ states('sensor.electricity_meter_current_phase_l2') }}A,
          L3: {{ states('sensor.electricity_meter_current_phase_l3') }}A
