- alias: Proximity-activated Light Study - on
  id: pal-study-on
  description: "There isn't a dedicated motion sensor here, but lighting up this area when someone is nearby is pretty useful."
  trigger:
    - platform: state
      entity_id: 
        - light.light_walk_in_closet
        - light.light_hall_2
      to: 'on'
  condition:
    # Can't check light groups here because they can't go "unavailable" if power is cut to the
    # entire group. Stay "on" if they were on before.
    # In this case, only checking 1 light is sufficient because they are always toggled together.
    - condition: state
      entity_id: light.light_study_spot_center
      state: 
        - 'off'
        - 'unavailable'
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_study
      data:
        brightness: 50 
        color_temp: 370
  mode: restart

- alias: Proximity-activated Light Study - off
  id: pal-study-off
  description: "Turn the study lights off again, unless they were changed manually."
  trigger:
    - platform: state
      entity_id: 
        - light.light_walk_in_closet
        - light.light_hall_2
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 
          - light.light_walk_in_closet
          - light.light_hall_2
        state: 'off'
      - condition: template
        value_template: '{{state_attr(''light.hue_light_group_study'', ''brightness'') | int(0) == 50}}'
  action:
    - service: light.turn_off
      target:
        entity_id: light.hue_light_group_study
  mode: restart

- alias: Proximity-activated Light Living + Kitchen - on
  id: pal-living-kitchen-on
  description: "There isn't a dedicated motion sensor here, but lighting up this area when someone is nearby is pretty useful."
  trigger:
    - platform: state
      entity_id: light.light_hall_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 
          - light.light_kitchen_m
          - light.light_arc
          - light.light_lightguide
          - light.light_dining_kitchen_side
        state: 
          - 'off'
          - 'unavailable'
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_kitchen
      data:
        brightness: 1
        color_temp: 455  # 2200k
    - service: light.turn_on
      target:
        entity_id: light.hue_light_group_living
      data:
        brightness: 50
        color_temp: 455
  mode: restart

- alias: Proximity-activated Light Living + Kitchen - off
  id: pal-living-kitchen-off
  description: "Turn the living room + kitchen lights off again, unless they were changed manually."
  trigger:
    - platform: state
      entity_id: light.light_hall_0
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{state_attr(''light.hue_light_group_kitchen'', ''brightness'') | int(0) == 1}}'
      - condition: template
        value_template: '{{state_attr(''light.hue_light_group_living'', ''brightness'') | int(0) == 50}}'
  action:
    - service: light.turn_off
      target:
        entity_id: 
          - light.hue_light_group_kitchen
          - light.hue_light_group_living
  mode: restart
