- alias: "Sleep mode: scheduled on"
  id: al-sleep-on
  trigger:
  - platform: time
    at: "23:00:00"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: scheduled off - daycare days"
  id: al-sleep-off-daycare
  trigger:
  - platform: time
    at: "07:00:00"
  condition:
  - condition: time
    weekday:
      - mon
      - thu
      - fri
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: scheduled off - non-daycare days"
  id: al-sleep-off-non-daycare
  trigger:
  - platform: time
    at: "08:00:00"
  condition:
  - condition: time
    weekday:
      - tue
      - wed
      - sat
      - sun
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
  mode: restart

- alias: "Sleep mode: toggle"
  id: "sleep-toggle"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
    - platform: homeassistant
      event: start  # in case the states aren't properly restored
  variables:
    sleep_mode: "{{ states('input_boolean.sleep_mode') }}"
  action:
    - service: "switch.turn_{{ sleep_mode }}"
      entity_id:
        - switch.adaptive_lighting_sleep_mode_motion
        - switch.adaptive_lighting_sleep_mode_motion_hall_0
        - switch.adaptive_lighting_sleep_mode_motion_floor_1
        - switch.adaptive_lighting_sleep_mode_motion_bathroom
    # Nest Protect pathlight is sufficient.
    - service: "automation.turn_{{ 'off' if sleep_mode == 'on' else 'on' }}"
      entity_id: automation.motion_activated_light_hall_1

- alias: "Sleep mode: toggle on, turn off light hall 1"
  id: "sleep-on"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: "on"
  action:
    - delay: "00:00:01"
    - service: light.turn_off
      entity_id: light.light_hall_1
    
- alias: "Sleep mode: toggle off, turn on light hall 1 if motion detected"
  id: "sleep-off"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.motion_hall_1_occupancy 
      state: "on"
  action:
    - delay: "00:00:01"
    - service: automation.trigger
      target:
        entity_id: automation.motion_activated_light_hall_1

