- alias: Alert Soil Humidity Heptapleurum
  id: alert-soil-humidity-heptapleurum
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_heptapleurum_humidity
      humidity_threshold_entity: input_number.soil_humidity_threshold_heptapleurum
      plant_name: Heptapleurum (Vingersboom)

- alias: Alert Soil Humidity Dracaena
  id: alert-soil-humidity-dracaena
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_dracaena_humidity
      humidity_threshold_entity: input_number.soil_humidity_threshold_dracaena
      plant_name: Dracaena (Drakenbloedboom)

- alias: Alert Soil Humidity Rhipsalis
  id: alert-soil-humidity-rhipsalis
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_rhipsalis_humidity
      humidity_threshold_entity: input_number.soil_humidity_threshold_rhipsalis
      plant_name: Rhipsalis (hangplant)

- alias: Alert Soil Humidity Spathiphyllum
  id: alert-soil-humidity-spathiphyllum
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_spathiphyllum_humidity
      humidity_threshold_entity: input_number.soil_humidity_threshold_spathiphyllum
      plant_name: Spathiphyllum (Peace Lily)

- alias: Alert Soil Humidity Alocasia
  id: alert-soil-humidity-alocasia
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_alocasia_humidity
      humidity_threshold_entity: input_number.soil_humidity_threshold_alocasia
      plant_name: Alocasia (Zebraplant)
