# Outside:

- alias: Alert Soil Outside Moisture
  id: alert-soil-outside-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_outside_moisture_average
      moisture_threshold_entity: input_number.soil_outside_moisture_threshold
      plant_name: Buiten (achtertuin rechts)
      instruction: ""

# Inside:

- alias: Alert Soil Calathea Moisture
  id: alert-soil-calathea-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_calathea_moisture_average
      moisture_threshold_entity: input_number.soil_calathea_moisture_threshold
      plant_name: Calathea Orbifolia (woonkamer)
      instruction: >-
        Houd grond licht vochtig.
        Houdt niet van natte voeten.
        Dus vaak een beetje water geven.
        Liefst regenwater op kamertemperatuur, anders bruine randen.

- alias: Alert Soil Drakenbloedboom Moisture
  id: alert-soil-drakenbloedboom-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_drakenbloedboom_moisture_average
      moisture_threshold_entity: input_number.soil_drakenbloedboom_moisture_threshold
      plant_name: Drakenbloedboom (woonkamer)
      instruction: >-
        Grond mag bijna helemaal uitdrogen.
        Houdt niet van natte voeten.

- alias: Alert Soil Koraalcactus Moisture
  id: alert-soil-koraalcactus-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_koraalcactus_moisture_average
      moisture_threshold_entity: input_number.soil_koraalcactus_moisture_threshold
      plant_name: Koraalcactus (woonkamer)
      instruction: >-
        Grond mag bijna helemaal uitdrogen.
        Liefst regenwater op kamertemperatuur.
        Houdt niet van natte voeten.

- alias: Alert Soil Lepelplant Moisture
  id: alert-soil-lepelplant-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_lepelplant_moisture_average
      moisture_threshold_entity: input_number.soil_lepelplant_moisture_threshold
      plant_name: Lepelplant (zolder)
      instruction: >-
        Verbruikt redelijk veel water.
        Niet gevoelig voor wortelrot.

- alias: Alert Soil Treurvijg Moisture
  id: alert-soil-treurvijg-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_treurvijg_moisture_average
      moisture_threshold_entity: input_number.soil_treurvijg_moisture_threshold
      plant_name: Treurvijg (zolder)
      instruction: >-
        Houd grond licht vochtig
        Houdt niet van natte voeten.
        Dus vaak een beetje water geven.
        Liefst regenwater op kamertemperatuur (houdt niet van kalk).

- alias: Alert Soil Dwergpalm Moisture
  id: alert-soil-dwergpalm-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_dwergpalm_moisture_average
      moisture_threshold_entity: input_number.soil_dwergpalm_moisture_threshold
      plant_name: Dwergpalm (slaapkamer)
      instruction: >-
        Houd grond licht vochtig
        Houdt niet van natte voeten.
        Dus vaak een beetje water geven.

- alias: Alert Soil Ginseng Moisture
  id: alert-soil-ginseng-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_ginseng_moisture_average
      moisture_threshold_entity: input_number.soil_ginseng_moisture_threshold
      plant_name: Ginseng (keuken)
      instruction: >-
        Houd grond licht vochtig
        Houdt niet van natte voeten.
        Dus vaak een beetje water geven.
        Liefst lauw water.

- alias: Alert Soil Monstera Moisture
  id: alert-soil-monstera-moisture
  use_blueprint:
    path: custom/soil_moisture_too_low.yaml
    input:
      moisture_entity: sensor.soil_monstera_moisture_average
      moisture_threshold_entity: input_number.soil_monstera_moisture_threshold
      plant_name: Monstera (zolder)
      instruction: >-
        Grond mag bijna helemaal uitdrogen.
        Houdt niet van natte voeten.
