- alias: Alert Soil Calathea Humidity
  id: alert-soil-calathea-humidity
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_calathea_humidity_average
      humidity_threshold_entity: input_number.soil_calathea_humidity_threshold
      plant_name: Calathea Orbifolia

- alias: Alert Soil Drakenbloedboom Humidity
  id: alert-soil-drakenbloedboom-humidity
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_drakenbloedboom_humidity_average
      humidity_threshold_entity: input_number.soil_drakenbloedboom_humidity_threshold
      plant_name: Drakenbloedboom

- alias: Alert Soil Koraalcactus Humidity
  id: alert-soil-koraalcactus-humidity
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_koraalcactus_humidity_average
      humidity_threshold_entity: input_number.soil_koraalcactus_humidity_threshold
      plant_name: Koraalcactus

- alias: Alert Soil Lepelplant Humidity
  id: alert-soil-lepelplant-humidity
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_lepelplant_humidity_average
      humidity_threshold_entity: input_number.soil_lepelplant_humidity_threshold
      plant_name: Lepelplant

- alias: Alert Soil Alocasia Humidity
  id: alert-soil-alocasia-humidity
  use_blueprint:
    path: custom/soil_humidity_too_low.yaml
    input:
      humidity_entity: sensor.soil_alocasia_humidity_average
      humidity_threshold_entity: input_number.soil_alocasia_humidity_threshold
      plant_name: Alocasia (Zebraplant)
