- alias: Alert solar production
  id: alert-solar-production
  trigger:
    - platform: sun
      event: sunset
      offset: "00:30:00"
  action:
    - service: notify.mobile_app_J12P
      data:
        title: Solar production today
        message: >
          Solarman: {{ states('sensor.solarman_daily_energy') | round(1) }} kWh,
          SolarEdge: {{ (states('sensor.solaredge_energy_today') | float(0) / 1000) | round(1) }} kWh
  mode: restart
