- alias: Alert solar production
  id: alert-solar-production
  trigger:
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service: notify.mobile_app_J12P
      data:
        title: Solar production today
        message: >
          Solarman: {{ states('sensor.solarman_daily_energy') }} kWh,
          SolarEdge: TODO
  mode: restart
