# TODOs: 
# - use derivative to be sure of dropping/rising temps outside.
# - perhaps add a timer at the end to prevent triggering again quickly. Once a day is sufficient.
#   But this may not even be needed with the delta indicator sensor and the 10 minute wait on the
#   state change.

- alias: Alert open windows to cool down
  id: 'alert-open-windows-to-cool-down'
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'yes'
      for: '00:10:00'
  condition: 
    - condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.home_average_temperature
        above: 22
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_2_hour
        below: 0
  action:
    - service: notify.notify
      data:
        title: Open windows
        message: >
          It's {{ states('sensor.home_average_temperature') }} °C inside and temperatures outside
          seem to be dropping below that. Open windows to cool the house down.
  mode: restart


- alias: Alert close windows to stay cool
  id: 'alert-close-windows-to-stay-cool'
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'no'
      for: '00:10:00'
  condition: 
    - condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.home_average_temperature
        above: 22
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_2_hour
        above: 0
  # known flaw: if the state change to 'no' happens when it's still below 22, but the
  # temperature rises above 22 sometime after that, the alert will never trigger.
  action:
    - service: notify.notify
      data:
        title: Close windows
        message: >
          It's {{ states('sensor.home_average_temperature') }} °C inside and temperatures outside
          seem to be rising above that. Close windows and curtains to stay cool.
  mode: restart

