- alias: Alert open windows to cool down
  id: 'alert-open-windows-to-cool-down'
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'yes'
      for: '00:05:00'
  condition: 
    - condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.home_average_temperature
        above: 22  # probably not worth the hassle if it's cooler than 22 deg already
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_hour
        below: 0
  action:
    - service: notify.notify
      data:
        title: Open windows
        message: >
          It's {{ states('sensor.home_average_temperature')|round(1) }} 째C inside.
          Temps outside are similar and dropping by {{ states('sensor.outside_temperature_change_per_hour')|round(1)|abs }} 째C/h.
    - delay: "12:00"  # Prevent it from triggering again today (temps may fluctuate)
  mode: restart


- alias: Alert close windows to stay cool
  id: 'alert-close-windows-to-stay-cool'
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'no'
      for: '00:05:00'
  condition: 
    - condition: and
      conditions:
      # TODO, maybe, if there's lots of false positives: check today's forecast, only trigger if actually gets hot today
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_hour
        above: 0
  action:
    - service: notify.notify
      data:
        title: Close windows
        message: >
          It's {{ states('sensor.home_average_temperature')|round(1) }} 째C inside.
          Temps outside are similar and rising by {{ states('sensor.outside_temperature_change_per_hour')|round(1) }} 째C/h.
    - delay: "12:00"  # Prevent it from triggering again today (temps may fluctuate)
  mode: restart

