- alias: Alert open windows to cool down
  id: alert-windows-open
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'yes'
      for: '00:05:00'
  condition:
    - condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.home_temperature
        above: 23  # probably not worth the hassle if it's cooler than 23 deg already
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_hour
        below: 0
  action:
    - service: notify.notify
      data:
        title: Open windows
        message: >
          It's {{ states('sensor.home_temperature') | float(-1) | round(1) }} 째C inside.
          Temps outside are similar and dropping by {{ states('sensor.outside_temperature_change_per_hour') | float(0) | round(1) | abs }} 째C/h.
    - delay:
        hours: 12 # Prevent it from triggering again today (temps may fluctuate)
  mode: queued


- alias: Alert close windows to stay cool
  id: alert-windows-close
  trigger:
    - platform: state
      entity_id: sensor.warmer_inside
      to: 'no'
      for: '00:05:00'
  condition:
    - condition: and
      conditions:
      # TODO, maybe, if there's lots of false positives: check today's forecast, only trigger if actually gets hot today
      - condition: numeric_state
        entity_id: sensor.outside_temperature_change_per_hour
        above: 0
  action:
    - service: notify.notify
      data:
        title: Close windows
        message: >
          It's {{ states('sensor.home_temperature') | float(-1) | round(1) }} 째C inside.
          Temps outside are similar and rising by {{ states('sensor.outside_temperature_change_per_hour') | float(-1) | round(1) }} 째C/h.
    - delay:
        hours: 12  # Prevent it from triggering again today (temps may fluctuate)
  mode: queued
