- alias: Alert Dishwasher Done
  id: 'alert-dishwasher-done'
  trigger:
    - platform: state 
      entity_id: sensor.dishwasher_power_filtered
      from: 'drying'
      to: 'off_closed'
      for: '00:01:00'
  action:
    - service: notify.notify
      data:
        title: Dishwasher
        message: 'Dishwasher appears to be done.'
  mode: restart

- alias: Alert Dishwasher Stuck
  id: 'alert-dishwasher-stuck'
  trigger:
    - platform: state 
      entity_id: sensor.dishwasher_power_filtered 
      from: 'washing'
      to: 'off_closed'
      for: '00:45:00'
  action:
    - service: notify.notify
      data:
        title: Dishwasher
        message: >
          Dishwasher appears to be in the failure mode where it skips the drying phase.
          Consider it done and expect wetter-than-usual contents.
  mode: restart

# The Dishwasher is a bit unreliable lately, and seems better if we power cycle it regularly.
- alias: Power Cycle Dishwasher at night when off
  id: 'power-cycle-dishwasher'
  trigger:
    - platform: time
      at: '04:00:00'  # Check quite late to minimize chance that it's running
  condition:
    - condition: and
      conditions:
        # may have turned if off manually, e.g. if on holiday. Leave off in that case. 
        - condition: state
          entity_id: switch.dishwasher
          state: 'on'
        - condition: state 
          entity_id: sensor.dishwasher_state
          state: 
            - 'off_door_open'
            - 'off_door_closed'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.dishwasher
    - delay: '01:00:00'
    - service: switch.turn_on
      target:
        entity_id: switch.dishwasher
  mode: restart

