- alias: Alert Dishwasher Done
  id: 'alert-dishwasher-done'
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power 
      above: 1000  # warming up
      for: '00:00:10'
  action:
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.dishwasher_power 
          below: 1
          for: '00:00:05'
    - service: notify.notify
      data:
        title: Dishwasher
        message: Dishwasher done
  mode: restart

# The Dishwasher is a bit unreliable lately, and seems better if we power cycle
# it before the next wash cycle.
- alias: Power Cycle Dishwasher at night when idle
  id: 'power-cycle-dishwasher'
  trigger:
    - platform: time
      at: '04:00:00'  # Check quite late to minimize chance that it's running
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.dishwasher
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.dishwasher_power
          below: 1  # Lowest power use during cycle is 1.4 W (drying). Standby consumption is 0.7 - 0.8 W.
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.dishwasher
    - delay: '02:00:00'  # turns back on at 6 
    - service: switch.turn_on
      target:
        entity_id: switch.dishwasher

