- alias: Alert Dishwasher Done
  id: 'alert-dishwasher-done'
  trigger:
    - platform: state 
      entity_id: sensor.dishwasher_power_filtered
      to: 'off'
      for: '00:01:00'
  action:
    - service: notify.notify
      data:
        title: Dishwasher
        message: Dishwasher switched to off state
  mode: restart

- alias: Alert Dishwasher Stuck
  id: 'alert-dishwasher-stuck'
  trigger:
    - platform: state 
      entity_id: sensor.dishwasher_power_filtered 
      from: 'washing'
      to: 'idle'
      for: '01:00:00'
  action:
    - service: notify.notify
      data:
        title: Dishwasher
        message: 'Dishwasher switched from washing to idle state and appears stuck - it may be done'
      # May want to power cycle directly.
  mode: restart

# The Dishwasher is a bit unreliable lately, and seems better if we power cycle it regularly.
- alias: Power Cycle Dishwasher at night when off
  id: 'power-cycle-dishwasher'
  trigger:
    - platform: time
      at: '04:00:00'  # Check quite late to minimize chance that it's running
  condition:
    - condition: and
      conditions:
        # may have turned if off manually, e.g. if on holiday. Leave off in that case. 
        - condition: state
          entity_id: switch.dishwasher
          state: 'on'
        - condition: state 
          entity_id: sensor.dishwasher_state
          state: 'off'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.dishwasher
    - delay: '02:00:00'  # turns back on at 6 
    - service: switch.turn_on
      target:
        entity_id: switch.dishwasher
  mode: restart

