- id: '1672576200799'
  alias: test hue wall switch
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2690a0977157622e90d45ed7a489344f
    type: action
    subtype: left_press
    discovery_id: 0x001788010cc472c2 action_left_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.light_lightguide
  mode: single
- id: '1672576331606'
  alias: tmp test wall switch
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2690a0977157622e90d45ed7a489344f
    type: action
    subtype: left_press
    discovery_id: 0x001788010cc472c2 action_left_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.light_lightguide
  mode: single
- id: '1672577430593'
  alias: New Automation
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2690a0977157622e90d45ed7a489344f
    type: action
    subtype: left_press
    discovery_id: 0x001788010cc472c2 action_left_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.light_lightguide
  mode: single
