
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
adaptive_lighting: !include adaptive_lighting.yaml

