
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensor/
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
adaptive_lighting: !include adaptive_lighting.yaml

template:
  - trigger:
      - platform: time_pattern
        seconds: 0
    sensor:  
      - name: Base Load power
        unique_id: base_load_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        state: >
          {{ states('input_number.base_load_power_wifi_aps') | float + 
             states('input_number.base_load_power_router') | float +
             states('input_number.base_load_power_fiber') | float +
             states('input_number.base_load_power_switch') | float +
             states('input_number.base_load_power_raspberry_pi') | float +
             states('input_number.base_load_power_z2m') | float +
             states('input_number.base_load_power_hue_lights') | float +
             states('input_number.base_load_power_hue_hub') | float +
             states('input_number.base_load_power_district_heating') | float +
             states('input_number.base_load_power_alarm') | float +
             states('input_number.base_load_power_central_ventilation') | float +
             states('input_number.base_load_power_smoke_detectors') | float +
             states('input_number.base_load_power_nanny_cams') | float +
             states('input_number.base_load_power_misc') | float
          }} 


  - trigger:
      - platform: time_pattern
        minutes: 59
    sensor:  
      - name: Base Load energy
        unique_id: base_load_energy
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.base_load_energy') | float(0) + states('sensor.base_load_power') | float(0) / 1000 }}"

  - sensor:
    - name: "Solarman Current Power"
      unique_id: "solarman_current_power"
      unit_of_measurement: 'W'
      state: "{{ state_attr('sensor.solarmanpv_inverter', 'Total_AC_Output_Power_(Active)') }}"
      state_class: measurement

    - name: "Solarman Lifetime Energy"
      unique_id: "solarman_lifetime_energy"
      unit_of_measurement: 'kWh'
      state: "{{ state_attr('sensor.solarmanpv_inverter', 'Cumulative_Production_(Active)') }}"
      state_class: total_increasing
      device_class: energy

    - name: "Solarman Daily Energy"
      unique_id: "solarman_daily_energy"
      unit_of_measurement: 'kWh'
      state: "{{ state_attr('sensor.solarmanpv_inverter', 'Daily_Production_(Active)') }}"
      state_class: total_increasing
      device_class: energy

mqtt:
  sensor:
    - state_topic: "solarmanpv/inverter/deviceState"
      name: "solarmanpv_inverter"
      unique_id: "solarmanpv_inverter"
      json_attributes_topic: "solarmanpv/inverter/attributes"


shell_command:
  front_camera_snap: curl http://192.168.2.40/snap.jpeg --output /media/front-snap.jpeg 
  front_camera_crop: ffmpeg -y -i /media/front-snap.jpeg -vf "crop=1000:800:100:600" /media/front-snap-cropped.jpeg
  
