
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

input_boolean:
  adaptive_lighting:
    name: Adaptive Lighting
    icon: mdi:theme-light-dark
  motion_activated_lights:
    name: Motion Activated Lights (TODO)
    icon: mdi:motion-sensor
  sleep_mode:
    name: Sleep Mode
    icon: mdi:sleep
  housekeeping_mode:
    # Toggle Adaptive Lighting + all motion sensors and set lights to max white.
    name: Housekeeping Mode (TODO)
    icon: mdi:broom

input_number:
  proximity_activated_light_living_brightness: 
    initial: 50
    min: 1
    max: 255
    step: 1
    mode: box
  proximity_activated_light_kitchen_brightness: 
    initial: 1
    min: 1
    max: 255
    step: 1
    mode: box
  proximity_activated_light_study_brightness: 
    initial: 50
    min: 1
    max: 255
    step: 1
    mode: box
  boiler_price_threshold:
    name: Boiler Price Thr.
    unit_of_measurement: "EUR/kWh"
    initial: 0.40
    min: 0.20
    step: 0.05
    max: 1.00
    mode: slider
  garden_lights_price_threshold:
    name: Garden Lights Price Thr.
    unit_of_measurement: "EUR/kWh"
    initial: 0.25
    min: 0.20
    step: 0.05
    max: 1.00
    mode: slider

adaptive_lighting:
- name: "motion"
  lights: 
    - light.light_hall_2 
    - light.light_toilet_0
    - light.light_walk_in_closet
    - light.light_laundry
    - light.light_dressing
  min_brightness: 50
  max_brightness: 80
  sleep_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
# Not needed in winter, but we probably want to use this to not get blasted with white light at 5 am in summer:
#  sunrise_time: "08:00:00" 
  # Not needed to keep adapting for lights that toggle often:
  only_once: true

# Under some circumstances, hall 0 dims itself instead of going off. Therefore, it needs its own section to be able
# to disable adaptive brightness. Also keep adjusting this (only_once: false, the default).
- name: "motion-hall-0"
  lights: 
    - light.light_hall_0
  min_brightness: 50
  max_brightness: 80
  sleep_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000

# specific lights on 1st floor are a little less bright due to sleeping kids, so it gets its own section.
- name: "motion-floor-1"
  lights: 
    - light.light_hall_1
    - light.light_toilet_1
  min_brightness: 10
  max_brightness: 50
  min_color_temp: 2200
  max_color_temp: 4000
#  sunrise_time: "08:00:00" 
  # Not needed to keep adapting for lights that toggle often:
  only_once: true
