
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

adaptive_lighting:
- name: "motion"
  lights: 
    - light.light_hall_0
    - light.light_hall_2 
    - light.light_toilet_0
    - light.light_walk_in_closet
    - light.light_laundry
    - light.light_dressing
  min_brightness: 50
  max_brightness: 80
  sleep_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
#  sunrise_time: "08:00:00" 
  # Not needed to keep adapting for lights that toggle often:
  only_once: true

# specific lights on 1st floor are a little less bright due to sleeping kids, so it gets its own section.
- name: "motion-floor-1"
  lights: 
    - light.light_hall_1
    - light.light_toilet_1
  min_brightness: 10
  max_brightness: 50
  min_color_temp: 2200
  max_color_temp: 4000
#  sunrise_time: "08:00:00" 
  # Not needed to keep adapting for lights that toggle often:
  only_once: true

