
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

adaptive_lighting:
- name: "living"
  lights: 
    - light.bloem
  prefer_rgb_color: false  # allows the color lamp to go below 2000k if min_color_temp allows it
  min_brightness: 30
  max_brightness: 80
  min_color_temp: 2000
  max_color_temp: 4000
  sunrise_time: "07:00:00" 
  sunset_offset: "00:30:00"
- name: "slaapkamer"  # Separate section, because we don't want automatic brightness control here. Only color.
  lights: 
#    - light.slaapkamer_1
#    - light.slaapkamer_2
#    - light.slaapkamer_3
#    - light.slaapkamer_chantal
    - light.slaapkamer_jori
  min_color_temp: 2000  # lights can only go down to 2200k
  max_color_temp: 4000
  sunrise_time: "07:00:00"
  sunset_offset: "00:30:00"

