proximity_activated_light_living_brightness: 
  initial: 50
  min: 1
  max: 255
  step: 1
  mode: box
proximity_activated_light_kitchen_brightness: 
  initial: 1
  min: 1
  max: 255
  step: 1
  mode: box
proximity_activated_light_study_brightness: 
  initial: 50
  min: 1
  max: 255
  step: 1
  mode: box
boiler_price_threshold:
  name: Boiler Price Thr.
  unit_of_measurement: "EUR/kWh"
  initial: 0.40
  min: 0.20
  step: 0.05
  max: 1.00
  mode: slider
garden_lights_price_threshold:
  name: Garden Lights Price Thr.
  unit_of_measurement: "EUR/kWh"
  initial: 0.25
  min: 0.20
  step: 0.05
  max: 1.00
  mode: slider
