adaptive_lighting:
  name: Adaptive Lighting
  icon: mdi:theme-light-dark
motion_activated_lights:
  name: Motion Activated Lights (TODO)
  icon: mdi:motion-sensor
sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep
housekeeping_mode:
  # Toggle Adaptive Lighting + all motion sensors and set lights to max white.
  name: Housekeeping Mode (TODO)
  icon: mdi:broom

