- platform: filter
  name: 'dishwasher power filtered'
  entity_id: 'sensor.dishwasher_power'
  filters:
    # We have unevenly spaced measurements so this seems more appropriate than low-pass filter.
    # However, it'll break down if we have only 1 measurement within the window_size.
    - filter: time_simple_moving_average
      window_size: "00:01:30"

# Infer dishwasher state: heating, washing, idle and off.
# 
# idle is a bit vague, and could mean a few things:
# - drying in the last stage of the wash cycle
# - off with door closed. After a normal wash cycle, power drops to 0.7 W which corresponds to
#   the off state. Opening the door doesn't affect power. However, closing it again makes power
#   jump to ~ 1.1 W which corresponds to idle  state.
# - "stuck" in a weird state after wash cycle. After an abnormal wash cycle, a LED blinks in the
#   panel and power doesn't drop to 0.7 W but stays at ~ 1.1 W.
#
# No idea what causes an abnormal wash cycle.
- platform: template
  sensors:
    dishwasher_state:
       unique_id: 'dishwasher_state_v1'
       friendly_name: Dishwasher
       value_template: >-
         {% if states('sensor.dishwasher_power_filtered')|float >= 1500 %}
           heating
         {% elif states('sensor.dishwasher_power_filtered')|float >= 2 %}
           washing
         {% elif states('sensor.dishwasher_power_filtered')|float >= 1 %}
           idle 
         {% else %}
           off
         {% endif %}

