- platform: filter
  name: 'dishwasher power filtered'
  entity_id: 'sensor.dishwasher_power'
  filters:
    # We have unevenly spaced measurements so this seems more appropriate than low-pass filter.
    # However, it'll break down if we have only 1 measurement within the window_size, so it should
    # not be too low.
    - filter: time_simple_moving_average
      window_size: "00:00:40"

- platform: template
  sensors:
    dishwasher_state:
       unique_id: 'dishwasher_state_v1'
       friendly_name: Dishwasher
       value_template: >-
         {% if states('sensor.dishwasher_power_filtered')|float >= 1500 %}
           heating
         {% elif states('sensor.dishwasher_power_filtered')|float >= 2 %}
           washing
         {% elif states('sensor.dishwasher_power_filtered')|float >= 1.34 %}
           drying
         {% elif states('sensor.dishwasher_power_filtered')|float >= 1 %}
           off_closed 
         {% else %}
           off_open
         {% endif %}

- platform: filter
  name: 'washing machine power filtered'
  entity_id: 'sensor.washing_machine_power'
  filters:
    - filter: time_simple_moving_average
      window_size: "00:00:40"

- platform: template
  sensors:
    washing_machine_state:
       unique_id: 'washing_machine_state_v1'
       friendly_name: Washing Machine
       value_template: >-
         {% if states('sensor.washing_machine_power_filtered')|float >= 500 %}
           heating
         {% elif states('sensor.washing_machine_power_filtered')|float >= 100 %}
           spinning
         {% elif states('sensor.washing_machine_power_filtered')|float >= 10 %}
           washing
         {% elif states('sensor.washing_machine_power_filtered')|float >= 1 %}
           idle
         {% else %}
           off
         {% endif %}


- platform: filter
  name: 'dryer power filtered'
  entity_id: 'sensor.dryer_power'
  filters:
    - filter: time_simple_moving_average
      window_size: "00:00:40"

- platform: template
  sensors:
    dryer_state:
       unique_id: 'dryer_state_v1'
       friendly_name: Dryer
       value_template: >-
         {% if states('sensor.dryer_power_filtered')|float >= 100 %}
           drying
         {% elif states('sensor.washing_machine_power_filtered')|float > 1 %}
           idle
         {% else %}
           off
         {% endif %}
