- platform: filter
  name: 'dishwasher power filtered'
  entity_id: 'sensor.dishwasher_power'
  filters:
    # We have unevenly spaced measurements so this seems more appropriate than low-pass filter.
    # However, it'll break down if we have only 1 measurement within the window_size.
    - filter: time_simple_moving_average
      window_size: "00:01:30"

- platform: template
  sensors:
    dishwasher_state:
       unique_id: 'dishwasher_state_v1'
       friendly_name: Dishwasher
       value_template: >-
         {% if states('sensor.dishwasher_power_filtered')|float >= 1500 %}
           heating
         {% elif states('sensor.dishwasher_power_filtered')|float >= 2 %}
           washing
         {% elif states('sensor.dishwasher_power_filtered')|float >= 1.3 %}
           drying
         {% elif states('sensor.dishwasher_power_filtered')|float >= 1 %}
           off_closed 
         {% else %}
           off_open
         {% endif %}

