version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
      - "./mosquitto-no-auth.conf:/mosquitto-no-auth.conf"
    ports:
      # 1883 is the default mqtt port, but it is in use by TeslaMate. Switch to 1884.
      - "1884:1884"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf -p 1884"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Defaults to 8080 but that is in use by Unify controller (and that was there first).
      - 8002:8080
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
