services:
  homeassistant:
    container_name: homeassistant
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    restart: unless-stopped
    privileged: true
    network_mode: host
