- platform: template
  sensors:
    electricity_meter_power_consumption_watt:
      friendly_name: Electricity Meter Power Consumption Watt
      value_template: "{{ states('sensor.electricity_meter_power_consumption') | float(0) * 1000 }}"
      unit_of_measurement: W

    known_power_use:
      friendly_name: Known Power Use 
      value_template: >
          {{ states('sensor.base_load_power') | float(0) + 
             states('sensor.plug_entertainment_power') | float(0) +
             states('sensor.plug_garden_lights_power') | float(0) +
             states('sensor.plug_workstation_power') | float(0) +
             states('sensor.plug_boiler_power') | float(0) +
             states('sensor.plug_roomba_power') | float(0) +
             states('sensor.plug_dishwasher_power') | float(0) +
             states('sensor.plug_washing_machine_power') | float(0) +
             states('sensor.plug_dryer_power') | float(0) +
             states('sensor.plug_floor_heating_pump_power') | float(0)
          }} 
      unit_of_measurement: W

- platform: filter
  name: 'Electricity Meter Power Consumption Watt filtered'
  entity_id: 'sensor.electricity_meter_power_consumption_watt'
  filters:
    - filter: time_simple_moving_average
      window_size: "00:00:30"

- platform: filter
  name: 'Known Power Use filtered'
  entity_id: 'sensor.known_power_use'
  filters:
    - filter: time_simple_moving_average
      window_size: "00:00:30"

- platform: average
  name: 'electricity_meter_power_production_hourly_average'
  unique_id: 'elec_hourly_avg'
  duration:
    hours: 1
  entities:
    - sensor.electricity_meter_power_production 
  precision: 3

