# Outside

- platform: filter
  name: Soil Outside humidity average
  unique_id: soil_outside_humidity_average
  entity_id: sensor.outside_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

# Inside

- platform: filter
  name: Soil Calathea humidity average
  unique_id: soil_calathea_humidity_average
  entity_id: sensor.soil_calathea_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Drakenbloedboom humidity average
  unique_id: soil_drakenbloedboom_humidity_average
  entity_id: sensor.soil_drakenbloedboom_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Koraalcactus humidity average
  unique_id: soil_koraalcactus_humidity_average
  entity_id: sensor.soil_koraalcactus_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Lepelplant humidity average
  unique_id: soil_lepelplant_humidity_average
  entity_id: sensor.soil_lepelplant_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"


- platform: filter
  name: Soil Treurvijg humidity average
  unique_id: soil_treurvijg_humidity_average
  entity_id: sensor.soil_treurvijg_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Dwergpalm humidity average
  unique_id: soil_dwergpalm_humidity_average
  entity_id: sensor.soil_dwergpalm_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Ginseng humidity average
  unique_id: soil_ginseng_humidity_average
  entity_id: sensor.soil_ginseng_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Monstera humidity average
  unique_id: soil_monstera_humidity_average
  entity_id: sensor.soil_monstera_humidity
  filters:
    - filter: time_simple_moving_average
      window_size: "02:00:00"

- platform: filter
  name: Soil Philodendron humidity average
  unique_id: soil_philodendron_humidity_average
  entity_id: sensor.soil_philodendron_humidity
  filters:
    - filter: time_simple_moving_average
      # This sensor is very noisy for some reason:
      window_size: "06:00:00"
