- platform: template
  sensors:
    outside_temperature:
      unit_of_measurement: "°C"
      unique_id: "outside_temperature"
      friendly_name: "Outside temperature"
      value_template: >-
        {{ state_attr("weather.buienradar", "temperature") | float(0) }}

- platform: template
  sensors:
    nighttime:
       unique_id: 'nighttime_v2'
       friendly_name: Nighttime
       value_template: >-
         {% if states('sun.sun') == "above_horizon" %}
           0
         {% else %}
           1
         {% endif %}
