name: Build and Test Home Assistant AMB

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install -y just
      - name: Build home-assistant-amb image
        run: just -d home-assistant-amb build
      - name: Test Home Assistant config
        run: just -d home-assistant-amb test-config
